
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Grupo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Grupo
 * 
 */
export type GrupoModel = runtime.Types.Result.DefaultSelection<Prisma.$GrupoPayload>

export type AggregateGrupo = {
  _count: GrupoCountAggregateOutputType | null
  _min: GrupoMinAggregateOutputType | null
  _max: GrupoMaxAggregateOutputType | null
}

export type GrupoMinAggregateOutputType = {
  id: string | null
  nome: string | null
  createdAt: Date | null
}

export type GrupoMaxAggregateOutputType = {
  id: string | null
  nome: string | null
  createdAt: Date | null
}

export type GrupoCountAggregateOutputType = {
  id: number
  nome: number
  createdAt: number
  _all: number
}


export type GrupoMinAggregateInputType = {
  id?: true
  nome?: true
  createdAt?: true
}

export type GrupoMaxAggregateInputType = {
  id?: true
  nome?: true
  createdAt?: true
}

export type GrupoCountAggregateInputType = {
  id?: true
  nome?: true
  createdAt?: true
  _all?: true
}

export type GrupoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Grupo to aggregate.
   */
  where?: Prisma.GrupoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Grupos to fetch.
   */
  orderBy?: Prisma.GrupoOrderByWithRelationInput | Prisma.GrupoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GrupoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Grupos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Grupos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Grupos
  **/
  _count?: true | GrupoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GrupoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GrupoMaxAggregateInputType
}

export type GetGrupoAggregateType<T extends GrupoAggregateArgs> = {
      [P in keyof T & keyof AggregateGrupo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGrupo[P]>
    : Prisma.GetScalarType<T[P], AggregateGrupo[P]>
}




export type GrupoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GrupoWhereInput
  orderBy?: Prisma.GrupoOrderByWithAggregationInput | Prisma.GrupoOrderByWithAggregationInput[]
  by: Prisma.GrupoScalarFieldEnum[] | Prisma.GrupoScalarFieldEnum
  having?: Prisma.GrupoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GrupoCountAggregateInputType | true
  _min?: GrupoMinAggregateInputType
  _max?: GrupoMaxAggregateInputType
}

export type GrupoGroupByOutputType = {
  id: string
  nome: string
  createdAt: Date
  _count: GrupoCountAggregateOutputType | null
  _min: GrupoMinAggregateOutputType | null
  _max: GrupoMaxAggregateOutputType | null
}

export type GetGrupoGroupByPayload<T extends GrupoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GrupoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GrupoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GrupoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GrupoGroupByOutputType[P]>
      }
    >
  >



export type GrupoWhereInput = {
  AND?: Prisma.GrupoWhereInput | Prisma.GrupoWhereInput[]
  OR?: Prisma.GrupoWhereInput[]
  NOT?: Prisma.GrupoWhereInput | Prisma.GrupoWhereInput[]
  id?: Prisma.StringFilter<"Grupo"> | string
  nome?: Prisma.StringFilter<"Grupo"> | string
  createdAt?: Prisma.DateTimeFilter<"Grupo"> | Date | string
  times?: Prisma.TimeListRelationFilter
  jogos?: Prisma.JogoListRelationFilter
  noticias?: Prisma.NoticiaListRelationFilter
}

export type GrupoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  times?: Prisma.TimeOrderByRelationAggregateInput
  jogos?: Prisma.JogoOrderByRelationAggregateInput
  noticias?: Prisma.NoticiaOrderByRelationAggregateInput
}

export type GrupoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GrupoWhereInput | Prisma.GrupoWhereInput[]
  OR?: Prisma.GrupoWhereInput[]
  NOT?: Prisma.GrupoWhereInput | Prisma.GrupoWhereInput[]
  nome?: Prisma.StringFilter<"Grupo"> | string
  createdAt?: Prisma.DateTimeFilter<"Grupo"> | Date | string
  times?: Prisma.TimeListRelationFilter
  jogos?: Prisma.JogoListRelationFilter
  noticias?: Prisma.NoticiaListRelationFilter
}, "id">

export type GrupoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.GrupoCountOrderByAggregateInput
  _max?: Prisma.GrupoMaxOrderByAggregateInput
  _min?: Prisma.GrupoMinOrderByAggregateInput
}

export type GrupoScalarWhereWithAggregatesInput = {
  AND?: Prisma.GrupoScalarWhereWithAggregatesInput | Prisma.GrupoScalarWhereWithAggregatesInput[]
  OR?: Prisma.GrupoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GrupoScalarWhereWithAggregatesInput | Prisma.GrupoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Grupo"> | string
  nome?: Prisma.StringWithAggregatesFilter<"Grupo"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Grupo"> | Date | string
}

export type GrupoCreateInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  times?: Prisma.TimeCreateNestedManyWithoutGrupoInput
  jogos?: Prisma.JogoCreateNestedManyWithoutGrupoInput
  noticias?: Prisma.NoticiaCreateNestedManyWithoutGrupoInput
}

export type GrupoUncheckedCreateInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  times?: Prisma.TimeUncheckedCreateNestedManyWithoutGrupoInput
  jogos?: Prisma.JogoUncheckedCreateNestedManyWithoutGrupoInput
  noticias?: Prisma.NoticiaUncheckedCreateNestedManyWithoutGrupoInput
}

export type GrupoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  times?: Prisma.TimeUpdateManyWithoutGrupoNestedInput
  jogos?: Prisma.JogoUpdateManyWithoutGrupoNestedInput
  noticias?: Prisma.NoticiaUpdateManyWithoutGrupoNestedInput
}

export type GrupoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  times?: Prisma.TimeUncheckedUpdateManyWithoutGrupoNestedInput
  jogos?: Prisma.JogoUncheckedUpdateManyWithoutGrupoNestedInput
  noticias?: Prisma.NoticiaUncheckedUpdateManyWithoutGrupoNestedInput
}

export type GrupoCreateManyInput = {
  id?: string
  nome: string
  createdAt?: Date | string
}

export type GrupoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GrupoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GrupoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GrupoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GrupoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type GrupoScalarRelationFilter = {
  is?: Prisma.GrupoWhereInput
  isNot?: Prisma.GrupoWhereInput
}

export type GrupoNullableScalarRelationFilter = {
  is?: Prisma.GrupoWhereInput | null
  isNot?: Prisma.GrupoWhereInput | null
}

export type GrupoCreateNestedOneWithoutTimesInput = {
  create?: Prisma.XOR<Prisma.GrupoCreateWithoutTimesInput, Prisma.GrupoUncheckedCreateWithoutTimesInput>
  connectOrCreate?: Prisma.GrupoCreateOrConnectWithoutTimesInput
  connect?: Prisma.GrupoWhereUniqueInput
}

export type GrupoUpdateOneRequiredWithoutTimesNestedInput = {
  create?: Prisma.XOR<Prisma.GrupoCreateWithoutTimesInput, Prisma.GrupoUncheckedCreateWithoutTimesInput>
  connectOrCreate?: Prisma.GrupoCreateOrConnectWithoutTimesInput
  upsert?: Prisma.GrupoUpsertWithoutTimesInput
  connect?: Prisma.GrupoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GrupoUpdateToOneWithWhereWithoutTimesInput, Prisma.GrupoUpdateWithoutTimesInput>, Prisma.GrupoUncheckedUpdateWithoutTimesInput>
}

export type GrupoCreateNestedOneWithoutJogosInput = {
  create?: Prisma.XOR<Prisma.GrupoCreateWithoutJogosInput, Prisma.GrupoUncheckedCreateWithoutJogosInput>
  connectOrCreate?: Prisma.GrupoCreateOrConnectWithoutJogosInput
  connect?: Prisma.GrupoWhereUniqueInput
}

export type GrupoUpdateOneRequiredWithoutJogosNestedInput = {
  create?: Prisma.XOR<Prisma.GrupoCreateWithoutJogosInput, Prisma.GrupoUncheckedCreateWithoutJogosInput>
  connectOrCreate?: Prisma.GrupoCreateOrConnectWithoutJogosInput
  upsert?: Prisma.GrupoUpsertWithoutJogosInput
  connect?: Prisma.GrupoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GrupoUpdateToOneWithWhereWithoutJogosInput, Prisma.GrupoUpdateWithoutJogosInput>, Prisma.GrupoUncheckedUpdateWithoutJogosInput>
}

export type GrupoCreateNestedOneWithoutNoticiasInput = {
  create?: Prisma.XOR<Prisma.GrupoCreateWithoutNoticiasInput, Prisma.GrupoUncheckedCreateWithoutNoticiasInput>
  connectOrCreate?: Prisma.GrupoCreateOrConnectWithoutNoticiasInput
  connect?: Prisma.GrupoWhereUniqueInput
}

export type GrupoUpdateOneWithoutNoticiasNestedInput = {
  create?: Prisma.XOR<Prisma.GrupoCreateWithoutNoticiasInput, Prisma.GrupoUncheckedCreateWithoutNoticiasInput>
  connectOrCreate?: Prisma.GrupoCreateOrConnectWithoutNoticiasInput
  upsert?: Prisma.GrupoUpsertWithoutNoticiasInput
  disconnect?: Prisma.GrupoWhereInput | boolean
  delete?: Prisma.GrupoWhereInput | boolean
  connect?: Prisma.GrupoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GrupoUpdateToOneWithWhereWithoutNoticiasInput, Prisma.GrupoUpdateWithoutNoticiasInput>, Prisma.GrupoUncheckedUpdateWithoutNoticiasInput>
}

export type GrupoCreateWithoutTimesInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  jogos?: Prisma.JogoCreateNestedManyWithoutGrupoInput
  noticias?: Prisma.NoticiaCreateNestedManyWithoutGrupoInput
}

export type GrupoUncheckedCreateWithoutTimesInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  jogos?: Prisma.JogoUncheckedCreateNestedManyWithoutGrupoInput
  noticias?: Prisma.NoticiaUncheckedCreateNestedManyWithoutGrupoInput
}

export type GrupoCreateOrConnectWithoutTimesInput = {
  where: Prisma.GrupoWhereUniqueInput
  create: Prisma.XOR<Prisma.GrupoCreateWithoutTimesInput, Prisma.GrupoUncheckedCreateWithoutTimesInput>
}

export type GrupoUpsertWithoutTimesInput = {
  update: Prisma.XOR<Prisma.GrupoUpdateWithoutTimesInput, Prisma.GrupoUncheckedUpdateWithoutTimesInput>
  create: Prisma.XOR<Prisma.GrupoCreateWithoutTimesInput, Prisma.GrupoUncheckedCreateWithoutTimesInput>
  where?: Prisma.GrupoWhereInput
}

export type GrupoUpdateToOneWithWhereWithoutTimesInput = {
  where?: Prisma.GrupoWhereInput
  data: Prisma.XOR<Prisma.GrupoUpdateWithoutTimesInput, Prisma.GrupoUncheckedUpdateWithoutTimesInput>
}

export type GrupoUpdateWithoutTimesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogos?: Prisma.JogoUpdateManyWithoutGrupoNestedInput
  noticias?: Prisma.NoticiaUpdateManyWithoutGrupoNestedInput
}

export type GrupoUncheckedUpdateWithoutTimesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogos?: Prisma.JogoUncheckedUpdateManyWithoutGrupoNestedInput
  noticias?: Prisma.NoticiaUncheckedUpdateManyWithoutGrupoNestedInput
}

export type GrupoCreateWithoutJogosInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  times?: Prisma.TimeCreateNestedManyWithoutGrupoInput
  noticias?: Prisma.NoticiaCreateNestedManyWithoutGrupoInput
}

export type GrupoUncheckedCreateWithoutJogosInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  times?: Prisma.TimeUncheckedCreateNestedManyWithoutGrupoInput
  noticias?: Prisma.NoticiaUncheckedCreateNestedManyWithoutGrupoInput
}

export type GrupoCreateOrConnectWithoutJogosInput = {
  where: Prisma.GrupoWhereUniqueInput
  create: Prisma.XOR<Prisma.GrupoCreateWithoutJogosInput, Prisma.GrupoUncheckedCreateWithoutJogosInput>
}

export type GrupoUpsertWithoutJogosInput = {
  update: Prisma.XOR<Prisma.GrupoUpdateWithoutJogosInput, Prisma.GrupoUncheckedUpdateWithoutJogosInput>
  create: Prisma.XOR<Prisma.GrupoCreateWithoutJogosInput, Prisma.GrupoUncheckedCreateWithoutJogosInput>
  where?: Prisma.GrupoWhereInput
}

export type GrupoUpdateToOneWithWhereWithoutJogosInput = {
  where?: Prisma.GrupoWhereInput
  data: Prisma.XOR<Prisma.GrupoUpdateWithoutJogosInput, Prisma.GrupoUncheckedUpdateWithoutJogosInput>
}

export type GrupoUpdateWithoutJogosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  times?: Prisma.TimeUpdateManyWithoutGrupoNestedInput
  noticias?: Prisma.NoticiaUpdateManyWithoutGrupoNestedInput
}

export type GrupoUncheckedUpdateWithoutJogosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  times?: Prisma.TimeUncheckedUpdateManyWithoutGrupoNestedInput
  noticias?: Prisma.NoticiaUncheckedUpdateManyWithoutGrupoNestedInput
}

export type GrupoCreateWithoutNoticiasInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  times?: Prisma.TimeCreateNestedManyWithoutGrupoInput
  jogos?: Prisma.JogoCreateNestedManyWithoutGrupoInput
}

export type GrupoUncheckedCreateWithoutNoticiasInput = {
  id?: string
  nome: string
  createdAt?: Date | string
  times?: Prisma.TimeUncheckedCreateNestedManyWithoutGrupoInput
  jogos?: Prisma.JogoUncheckedCreateNestedManyWithoutGrupoInput
}

export type GrupoCreateOrConnectWithoutNoticiasInput = {
  where: Prisma.GrupoWhereUniqueInput
  create: Prisma.XOR<Prisma.GrupoCreateWithoutNoticiasInput, Prisma.GrupoUncheckedCreateWithoutNoticiasInput>
}

export type GrupoUpsertWithoutNoticiasInput = {
  update: Prisma.XOR<Prisma.GrupoUpdateWithoutNoticiasInput, Prisma.GrupoUncheckedUpdateWithoutNoticiasInput>
  create: Prisma.XOR<Prisma.GrupoCreateWithoutNoticiasInput, Prisma.GrupoUncheckedCreateWithoutNoticiasInput>
  where?: Prisma.GrupoWhereInput
}

export type GrupoUpdateToOneWithWhereWithoutNoticiasInput = {
  where?: Prisma.GrupoWhereInput
  data: Prisma.XOR<Prisma.GrupoUpdateWithoutNoticiasInput, Prisma.GrupoUncheckedUpdateWithoutNoticiasInput>
}

export type GrupoUpdateWithoutNoticiasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  times?: Prisma.TimeUpdateManyWithoutGrupoNestedInput
  jogos?: Prisma.JogoUpdateManyWithoutGrupoNestedInput
}

export type GrupoUncheckedUpdateWithoutNoticiasInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  times?: Prisma.TimeUncheckedUpdateManyWithoutGrupoNestedInput
  jogos?: Prisma.JogoUncheckedUpdateManyWithoutGrupoNestedInput
}


/**
 * Count Type GrupoCountOutputType
 */

export type GrupoCountOutputType = {
  times: number
  jogos: number
  noticias: number
}

export type GrupoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  times?: boolean | GrupoCountOutputTypeCountTimesArgs
  jogos?: boolean | GrupoCountOutputTypeCountJogosArgs
  noticias?: boolean | GrupoCountOutputTypeCountNoticiasArgs
}

/**
 * GrupoCountOutputType without action
 */
export type GrupoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GrupoCountOutputType
   */
  select?: Prisma.GrupoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GrupoCountOutputType without action
 */
export type GrupoCountOutputTypeCountTimesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeWhereInput
}

/**
 * GrupoCountOutputType without action
 */
export type GrupoCountOutputTypeCountJogosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JogoWhereInput
}

/**
 * GrupoCountOutputType without action
 */
export type GrupoCountOutputTypeCountNoticiasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NoticiaWhereInput
}


export type GrupoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  createdAt?: boolean
  times?: boolean | Prisma.Grupo$timesArgs<ExtArgs>
  jogos?: boolean | Prisma.Grupo$jogosArgs<ExtArgs>
  noticias?: boolean | Prisma.Grupo$noticiasArgs<ExtArgs>
  _count?: boolean | Prisma.GrupoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["grupo"]>

export type GrupoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["grupo"]>

export type GrupoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["grupo"]>

export type GrupoSelectScalar = {
  id?: boolean
  nome?: boolean
  createdAt?: boolean
}

export type GrupoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "createdAt", ExtArgs["result"]["grupo"]>
export type GrupoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  times?: boolean | Prisma.Grupo$timesArgs<ExtArgs>
  jogos?: boolean | Prisma.Grupo$jogosArgs<ExtArgs>
  noticias?: boolean | Prisma.Grupo$noticiasArgs<ExtArgs>
  _count?: boolean | Prisma.GrupoCountOutputTypeDefaultArgs<ExtArgs>
}
export type GrupoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type GrupoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $GrupoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Grupo"
  objects: {
    times: Prisma.$TimePayload<ExtArgs>[]
    jogos: Prisma.$JogoPayload<ExtArgs>[]
    noticias: Prisma.$NoticiaPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nome: string
    createdAt: Date
  }, ExtArgs["result"]["grupo"]>
  composites: {}
}

export type GrupoGetPayload<S extends boolean | null | undefined | GrupoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GrupoPayload, S>

export type GrupoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GrupoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GrupoCountAggregateInputType | true
  }

export interface GrupoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Grupo'], meta: { name: 'Grupo' } }
  /**
   * Find zero or one Grupo that matches the filter.
   * @param {GrupoFindUniqueArgs} args - Arguments to find a Grupo
   * @example
   * // Get one Grupo
   * const grupo = await prisma.grupo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GrupoFindUniqueArgs>(args: Prisma.SelectSubset<T, GrupoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Grupo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GrupoFindUniqueOrThrowArgs} args - Arguments to find a Grupo
   * @example
   * // Get one Grupo
   * const grupo = await prisma.grupo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GrupoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GrupoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Grupo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoFindFirstArgs} args - Arguments to find a Grupo
   * @example
   * // Get one Grupo
   * const grupo = await prisma.grupo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GrupoFindFirstArgs>(args?: Prisma.SelectSubset<T, GrupoFindFirstArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Grupo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoFindFirstOrThrowArgs} args - Arguments to find a Grupo
   * @example
   * // Get one Grupo
   * const grupo = await prisma.grupo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GrupoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GrupoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Grupos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Grupos
   * const grupos = await prisma.grupo.findMany()
   * 
   * // Get first 10 Grupos
   * const grupos = await prisma.grupo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const grupoWithIdOnly = await prisma.grupo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GrupoFindManyArgs>(args?: Prisma.SelectSubset<T, GrupoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Grupo.
   * @param {GrupoCreateArgs} args - Arguments to create a Grupo.
   * @example
   * // Create one Grupo
   * const Grupo = await prisma.grupo.create({
   *   data: {
   *     // ... data to create a Grupo
   *   }
   * })
   * 
   */
  create<T extends GrupoCreateArgs>(args: Prisma.SelectSubset<T, GrupoCreateArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Grupos.
   * @param {GrupoCreateManyArgs} args - Arguments to create many Grupos.
   * @example
   * // Create many Grupos
   * const grupo = await prisma.grupo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GrupoCreateManyArgs>(args?: Prisma.SelectSubset<T, GrupoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Grupos and returns the data saved in the database.
   * @param {GrupoCreateManyAndReturnArgs} args - Arguments to create many Grupos.
   * @example
   * // Create many Grupos
   * const grupo = await prisma.grupo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Grupos and only return the `id`
   * const grupoWithIdOnly = await prisma.grupo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GrupoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GrupoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Grupo.
   * @param {GrupoDeleteArgs} args - Arguments to delete one Grupo.
   * @example
   * // Delete one Grupo
   * const Grupo = await prisma.grupo.delete({
   *   where: {
   *     // ... filter to delete one Grupo
   *   }
   * })
   * 
   */
  delete<T extends GrupoDeleteArgs>(args: Prisma.SelectSubset<T, GrupoDeleteArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Grupo.
   * @param {GrupoUpdateArgs} args - Arguments to update one Grupo.
   * @example
   * // Update one Grupo
   * const grupo = await prisma.grupo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GrupoUpdateArgs>(args: Prisma.SelectSubset<T, GrupoUpdateArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Grupos.
   * @param {GrupoDeleteManyArgs} args - Arguments to filter Grupos to delete.
   * @example
   * // Delete a few Grupos
   * const { count } = await prisma.grupo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GrupoDeleteManyArgs>(args?: Prisma.SelectSubset<T, GrupoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Grupos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Grupos
   * const grupo = await prisma.grupo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GrupoUpdateManyArgs>(args: Prisma.SelectSubset<T, GrupoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Grupos and returns the data updated in the database.
   * @param {GrupoUpdateManyAndReturnArgs} args - Arguments to update many Grupos.
   * @example
   * // Update many Grupos
   * const grupo = await prisma.grupo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Grupos and only return the `id`
   * const grupoWithIdOnly = await prisma.grupo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GrupoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GrupoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Grupo.
   * @param {GrupoUpsertArgs} args - Arguments to update or create a Grupo.
   * @example
   * // Update or create a Grupo
   * const grupo = await prisma.grupo.upsert({
   *   create: {
   *     // ... data to create a Grupo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Grupo we want to update
   *   }
   * })
   */
  upsert<T extends GrupoUpsertArgs>(args: Prisma.SelectSubset<T, GrupoUpsertArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Grupos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoCountArgs} args - Arguments to filter Grupos to count.
   * @example
   * // Count the number of Grupos
   * const count = await prisma.grupo.count({
   *   where: {
   *     // ... the filter for the Grupos we want to count
   *   }
   * })
  **/
  count<T extends GrupoCountArgs>(
    args?: Prisma.Subset<T, GrupoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GrupoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Grupo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GrupoAggregateArgs>(args: Prisma.Subset<T, GrupoAggregateArgs>): Prisma.PrismaPromise<GetGrupoAggregateType<T>>

  /**
   * Group by Grupo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GrupoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GrupoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GrupoGroupByArgs['orderBy'] }
      : { orderBy?: GrupoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GrupoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGrupoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Grupo model
 */
readonly fields: GrupoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Grupo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GrupoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  times<T extends Prisma.Grupo$timesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Grupo$timesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  jogos<T extends Prisma.Grupo$jogosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Grupo$jogosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JogoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  noticias<T extends Prisma.Grupo$noticiasArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Grupo$noticiasArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Grupo model
 */
export interface GrupoFieldRefs {
  readonly id: Prisma.FieldRef<"Grupo", 'String'>
  readonly nome: Prisma.FieldRef<"Grupo", 'String'>
  readonly createdAt: Prisma.FieldRef<"Grupo", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Grupo findUnique
 */
export type GrupoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * Filter, which Grupo to fetch.
   */
  where: Prisma.GrupoWhereUniqueInput
}

/**
 * Grupo findUniqueOrThrow
 */
export type GrupoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * Filter, which Grupo to fetch.
   */
  where: Prisma.GrupoWhereUniqueInput
}

/**
 * Grupo findFirst
 */
export type GrupoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * Filter, which Grupo to fetch.
   */
  where?: Prisma.GrupoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Grupos to fetch.
   */
  orderBy?: Prisma.GrupoOrderByWithRelationInput | Prisma.GrupoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Grupos.
   */
  cursor?: Prisma.GrupoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Grupos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Grupos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Grupos.
   */
  distinct?: Prisma.GrupoScalarFieldEnum | Prisma.GrupoScalarFieldEnum[]
}

/**
 * Grupo findFirstOrThrow
 */
export type GrupoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * Filter, which Grupo to fetch.
   */
  where?: Prisma.GrupoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Grupos to fetch.
   */
  orderBy?: Prisma.GrupoOrderByWithRelationInput | Prisma.GrupoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Grupos.
   */
  cursor?: Prisma.GrupoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Grupos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Grupos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Grupos.
   */
  distinct?: Prisma.GrupoScalarFieldEnum | Prisma.GrupoScalarFieldEnum[]
}

/**
 * Grupo findMany
 */
export type GrupoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * Filter, which Grupos to fetch.
   */
  where?: Prisma.GrupoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Grupos to fetch.
   */
  orderBy?: Prisma.GrupoOrderByWithRelationInput | Prisma.GrupoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Grupos.
   */
  cursor?: Prisma.GrupoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Grupos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Grupos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Grupos.
   */
  distinct?: Prisma.GrupoScalarFieldEnum | Prisma.GrupoScalarFieldEnum[]
}

/**
 * Grupo create
 */
export type GrupoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * The data needed to create a Grupo.
   */
  data: Prisma.XOR<Prisma.GrupoCreateInput, Prisma.GrupoUncheckedCreateInput>
}

/**
 * Grupo createMany
 */
export type GrupoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Grupos.
   */
  data: Prisma.GrupoCreateManyInput | Prisma.GrupoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Grupo createManyAndReturn
 */
export type GrupoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * The data used to create many Grupos.
   */
  data: Prisma.GrupoCreateManyInput | Prisma.GrupoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Grupo update
 */
export type GrupoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * The data needed to update a Grupo.
   */
  data: Prisma.XOR<Prisma.GrupoUpdateInput, Prisma.GrupoUncheckedUpdateInput>
  /**
   * Choose, which Grupo to update.
   */
  where: Prisma.GrupoWhereUniqueInput
}

/**
 * Grupo updateMany
 */
export type GrupoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Grupos.
   */
  data: Prisma.XOR<Prisma.GrupoUpdateManyMutationInput, Prisma.GrupoUncheckedUpdateManyInput>
  /**
   * Filter which Grupos to update
   */
  where?: Prisma.GrupoWhereInput
  /**
   * Limit how many Grupos to update.
   */
  limit?: number
}

/**
 * Grupo updateManyAndReturn
 */
export type GrupoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * The data used to update Grupos.
   */
  data: Prisma.XOR<Prisma.GrupoUpdateManyMutationInput, Prisma.GrupoUncheckedUpdateManyInput>
  /**
   * Filter which Grupos to update
   */
  where?: Prisma.GrupoWhereInput
  /**
   * Limit how many Grupos to update.
   */
  limit?: number
}

/**
 * Grupo upsert
 */
export type GrupoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * The filter to search for the Grupo to update in case it exists.
   */
  where: Prisma.GrupoWhereUniqueInput
  /**
   * In case the Grupo found by the `where` argument doesn't exist, create a new Grupo with this data.
   */
  create: Prisma.XOR<Prisma.GrupoCreateInput, Prisma.GrupoUncheckedCreateInput>
  /**
   * In case the Grupo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GrupoUpdateInput, Prisma.GrupoUncheckedUpdateInput>
}

/**
 * Grupo delete
 */
export type GrupoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  /**
   * Filter which Grupo to delete.
   */
  where: Prisma.GrupoWhereUniqueInput
}

/**
 * Grupo deleteMany
 */
export type GrupoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Grupos to delete
   */
  where?: Prisma.GrupoWhereInput
  /**
   * Limit how many Grupos to delete.
   */
  limit?: number
}

/**
 * Grupo.times
 */
export type Grupo$timesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  where?: Prisma.TimeWhereInput
  orderBy?: Prisma.TimeOrderByWithRelationInput | Prisma.TimeOrderByWithRelationInput[]
  cursor?: Prisma.TimeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * Grupo.jogos
 */
export type Grupo$jogosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jogo
   */
  select?: Prisma.JogoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jogo
   */
  omit?: Prisma.JogoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JogoInclude<ExtArgs> | null
  where?: Prisma.JogoWhereInput
  orderBy?: Prisma.JogoOrderByWithRelationInput | Prisma.JogoOrderByWithRelationInput[]
  cursor?: Prisma.JogoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JogoScalarFieldEnum | Prisma.JogoScalarFieldEnum[]
}

/**
 * Grupo.noticias
 */
export type Grupo$noticiasArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  where?: Prisma.NoticiaWhereInput
  orderBy?: Prisma.NoticiaOrderByWithRelationInput | Prisma.NoticiaOrderByWithRelationInput[]
  cursor?: Prisma.NoticiaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NoticiaScalarFieldEnum | Prisma.NoticiaScalarFieldEnum[]
}

/**
 * Grupo without action
 */
export type GrupoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
}
