
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LogAdmin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model LogAdmin
 * 
 */
export type LogAdminModel = runtime.Types.Result.DefaultSelection<Prisma.$LogAdminPayload>

export type AggregateLogAdmin = {
  _count: LogAdminCountAggregateOutputType | null
  _min: LogAdminMinAggregateOutputType | null
  _max: LogAdminMaxAggregateOutputType | null
}

export type LogAdminMinAggregateOutputType = {
  id: string | null
  adminId: string | null
  acao: $Enums.AcaoLog | null
  entidade: $Enums.EntidadeLog | null
  entidadeId: string | null
  criadoEm: Date | null
}

export type LogAdminMaxAggregateOutputType = {
  id: string | null
  adminId: string | null
  acao: $Enums.AcaoLog | null
  entidade: $Enums.EntidadeLog | null
  entidadeId: string | null
  criadoEm: Date | null
}

export type LogAdminCountAggregateOutputType = {
  id: number
  adminId: number
  acao: number
  entidade: number
  entidadeId: number
  detalhes: number
  criadoEm: number
  _all: number
}


export type LogAdminMinAggregateInputType = {
  id?: true
  adminId?: true
  acao?: true
  entidade?: true
  entidadeId?: true
  criadoEm?: true
}

export type LogAdminMaxAggregateInputType = {
  id?: true
  adminId?: true
  acao?: true
  entidade?: true
  entidadeId?: true
  criadoEm?: true
}

export type LogAdminCountAggregateInputType = {
  id?: true
  adminId?: true
  acao?: true
  entidade?: true
  entidadeId?: true
  detalhes?: true
  criadoEm?: true
  _all?: true
}

export type LogAdminAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LogAdmin to aggregate.
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogAdmins to fetch.
   */
  orderBy?: Prisma.LogAdminOrderByWithRelationInput | Prisma.LogAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LogAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LogAdmins
  **/
  _count?: true | LogAdminCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LogAdminMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LogAdminMaxAggregateInputType
}

export type GetLogAdminAggregateType<T extends LogAdminAggregateArgs> = {
      [P in keyof T & keyof AggregateLogAdmin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLogAdmin[P]>
    : Prisma.GetScalarType<T[P], AggregateLogAdmin[P]>
}




export type LogAdminGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LogAdminWhereInput
  orderBy?: Prisma.LogAdminOrderByWithAggregationInput | Prisma.LogAdminOrderByWithAggregationInput[]
  by: Prisma.LogAdminScalarFieldEnum[] | Prisma.LogAdminScalarFieldEnum
  having?: Prisma.LogAdminScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LogAdminCountAggregateInputType | true
  _min?: LogAdminMinAggregateInputType
  _max?: LogAdminMaxAggregateInputType
}

export type LogAdminGroupByOutputType = {
  id: string
  adminId: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId: string | null
  detalhes: runtime.JsonValue | null
  criadoEm: Date
  _count: LogAdminCountAggregateOutputType | null
  _min: LogAdminMinAggregateOutputType | null
  _max: LogAdminMaxAggregateOutputType | null
}

export type GetLogAdminGroupByPayload<T extends LogAdminGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LogAdminGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LogAdminGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LogAdminGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LogAdminGroupByOutputType[P]>
      }
    >
  >



export type LogAdminWhereInput = {
  AND?: Prisma.LogAdminWhereInput | Prisma.LogAdminWhereInput[]
  OR?: Prisma.LogAdminWhereInput[]
  NOT?: Prisma.LogAdminWhereInput | Prisma.LogAdminWhereInput[]
  id?: Prisma.StringFilter<"LogAdmin"> | string
  adminId?: Prisma.StringFilter<"LogAdmin"> | string
  acao?: Prisma.EnumAcaoLogFilter<"LogAdmin"> | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFilter<"LogAdmin"> | $Enums.EntidadeLog
  entidadeId?: Prisma.StringNullableFilter<"LogAdmin"> | string | null
  detalhes?: Prisma.JsonNullableFilter<"LogAdmin">
  criadoEm?: Prisma.DateTimeFilter<"LogAdmin"> | Date | string
  admin?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LogAdminOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  acao?: Prisma.SortOrder
  entidade?: Prisma.SortOrder
  entidadeId?: Prisma.SortOrderInput | Prisma.SortOrder
  detalhes?: Prisma.SortOrderInput | Prisma.SortOrder
  criadoEm?: Prisma.SortOrder
  admin?: Prisma.UserOrderByWithRelationInput
}

export type LogAdminWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.LogAdminWhereInput | Prisma.LogAdminWhereInput[]
  OR?: Prisma.LogAdminWhereInput[]
  NOT?: Prisma.LogAdminWhereInput | Prisma.LogAdminWhereInput[]
  adminId?: Prisma.StringFilter<"LogAdmin"> | string
  acao?: Prisma.EnumAcaoLogFilter<"LogAdmin"> | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFilter<"LogAdmin"> | $Enums.EntidadeLog
  entidadeId?: Prisma.StringNullableFilter<"LogAdmin"> | string | null
  detalhes?: Prisma.JsonNullableFilter<"LogAdmin">
  criadoEm?: Prisma.DateTimeFilter<"LogAdmin"> | Date | string
  admin?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type LogAdminOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  acao?: Prisma.SortOrder
  entidade?: Prisma.SortOrder
  entidadeId?: Prisma.SortOrderInput | Prisma.SortOrder
  detalhes?: Prisma.SortOrderInput | Prisma.SortOrder
  criadoEm?: Prisma.SortOrder
  _count?: Prisma.LogAdminCountOrderByAggregateInput
  _max?: Prisma.LogAdminMaxOrderByAggregateInput
  _min?: Prisma.LogAdminMinOrderByAggregateInput
}

export type LogAdminScalarWhereWithAggregatesInput = {
  AND?: Prisma.LogAdminScalarWhereWithAggregatesInput | Prisma.LogAdminScalarWhereWithAggregatesInput[]
  OR?: Prisma.LogAdminScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LogAdminScalarWhereWithAggregatesInput | Prisma.LogAdminScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LogAdmin"> | string
  adminId?: Prisma.StringWithAggregatesFilter<"LogAdmin"> | string
  acao?: Prisma.EnumAcaoLogWithAggregatesFilter<"LogAdmin"> | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogWithAggregatesFilter<"LogAdmin"> | $Enums.EntidadeLog
  entidadeId?: Prisma.StringNullableWithAggregatesFilter<"LogAdmin"> | string | null
  detalhes?: Prisma.JsonNullableWithAggregatesFilter<"LogAdmin">
  criadoEm?: Prisma.DateTimeWithAggregatesFilter<"LogAdmin"> | Date | string
}

export type LogAdminCreateInput = {
  id?: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId?: string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Date | string
  admin: Prisma.UserCreateNestedOneWithoutLogsInput
}

export type LogAdminUncheckedCreateInput = {
  id?: string
  adminId: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId?: string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Date | string
}

export type LogAdminUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  admin?: Prisma.UserUpdateOneRequiredWithoutLogsNestedInput
}

export type LogAdminUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adminId?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogAdminCreateManyInput = {
  id?: string
  adminId: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId?: string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Date | string
}

export type LogAdminUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogAdminUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  adminId?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogAdminListRelationFilter = {
  every?: Prisma.LogAdminWhereInput
  some?: Prisma.LogAdminWhereInput
  none?: Prisma.LogAdminWhereInput
}

export type LogAdminOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LogAdminCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  acao?: Prisma.SortOrder
  entidade?: Prisma.SortOrder
  entidadeId?: Prisma.SortOrder
  detalhes?: Prisma.SortOrder
  criadoEm?: Prisma.SortOrder
}

export type LogAdminMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  acao?: Prisma.SortOrder
  entidade?: Prisma.SortOrder
  entidadeId?: Prisma.SortOrder
  criadoEm?: Prisma.SortOrder
}

export type LogAdminMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  adminId?: Prisma.SortOrder
  acao?: Prisma.SortOrder
  entidade?: Prisma.SortOrder
  entidadeId?: Prisma.SortOrder
  criadoEm?: Prisma.SortOrder
}

export type LogAdminCreateNestedManyWithoutAdminInput = {
  create?: Prisma.XOR<Prisma.LogAdminCreateWithoutAdminInput, Prisma.LogAdminUncheckedCreateWithoutAdminInput> | Prisma.LogAdminCreateWithoutAdminInput[] | Prisma.LogAdminUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.LogAdminCreateOrConnectWithoutAdminInput | Prisma.LogAdminCreateOrConnectWithoutAdminInput[]
  createMany?: Prisma.LogAdminCreateManyAdminInputEnvelope
  connect?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
}

export type LogAdminUncheckedCreateNestedManyWithoutAdminInput = {
  create?: Prisma.XOR<Prisma.LogAdminCreateWithoutAdminInput, Prisma.LogAdminUncheckedCreateWithoutAdminInput> | Prisma.LogAdminCreateWithoutAdminInput[] | Prisma.LogAdminUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.LogAdminCreateOrConnectWithoutAdminInput | Prisma.LogAdminCreateOrConnectWithoutAdminInput[]
  createMany?: Prisma.LogAdminCreateManyAdminInputEnvelope
  connect?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
}

export type LogAdminUpdateManyWithoutAdminNestedInput = {
  create?: Prisma.XOR<Prisma.LogAdminCreateWithoutAdminInput, Prisma.LogAdminUncheckedCreateWithoutAdminInput> | Prisma.LogAdminCreateWithoutAdminInput[] | Prisma.LogAdminUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.LogAdminCreateOrConnectWithoutAdminInput | Prisma.LogAdminCreateOrConnectWithoutAdminInput[]
  upsert?: Prisma.LogAdminUpsertWithWhereUniqueWithoutAdminInput | Prisma.LogAdminUpsertWithWhereUniqueWithoutAdminInput[]
  createMany?: Prisma.LogAdminCreateManyAdminInputEnvelope
  set?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  disconnect?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  delete?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  connect?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  update?: Prisma.LogAdminUpdateWithWhereUniqueWithoutAdminInput | Prisma.LogAdminUpdateWithWhereUniqueWithoutAdminInput[]
  updateMany?: Prisma.LogAdminUpdateManyWithWhereWithoutAdminInput | Prisma.LogAdminUpdateManyWithWhereWithoutAdminInput[]
  deleteMany?: Prisma.LogAdminScalarWhereInput | Prisma.LogAdminScalarWhereInput[]
}

export type LogAdminUncheckedUpdateManyWithoutAdminNestedInput = {
  create?: Prisma.XOR<Prisma.LogAdminCreateWithoutAdminInput, Prisma.LogAdminUncheckedCreateWithoutAdminInput> | Prisma.LogAdminCreateWithoutAdminInput[] | Prisma.LogAdminUncheckedCreateWithoutAdminInput[]
  connectOrCreate?: Prisma.LogAdminCreateOrConnectWithoutAdminInput | Prisma.LogAdminCreateOrConnectWithoutAdminInput[]
  upsert?: Prisma.LogAdminUpsertWithWhereUniqueWithoutAdminInput | Prisma.LogAdminUpsertWithWhereUniqueWithoutAdminInput[]
  createMany?: Prisma.LogAdminCreateManyAdminInputEnvelope
  set?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  disconnect?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  delete?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  connect?: Prisma.LogAdminWhereUniqueInput | Prisma.LogAdminWhereUniqueInput[]
  update?: Prisma.LogAdminUpdateWithWhereUniqueWithoutAdminInput | Prisma.LogAdminUpdateWithWhereUniqueWithoutAdminInput[]
  updateMany?: Prisma.LogAdminUpdateManyWithWhereWithoutAdminInput | Prisma.LogAdminUpdateManyWithWhereWithoutAdminInput[]
  deleteMany?: Prisma.LogAdminScalarWhereInput | Prisma.LogAdminScalarWhereInput[]
}

export type EnumAcaoLogFieldUpdateOperationsInput = {
  set?: $Enums.AcaoLog
}

export type EnumEntidadeLogFieldUpdateOperationsInput = {
  set?: $Enums.EntidadeLog
}

export type LogAdminCreateWithoutAdminInput = {
  id?: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId?: string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Date | string
}

export type LogAdminUncheckedCreateWithoutAdminInput = {
  id?: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId?: string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Date | string
}

export type LogAdminCreateOrConnectWithoutAdminInput = {
  where: Prisma.LogAdminWhereUniqueInput
  create: Prisma.XOR<Prisma.LogAdminCreateWithoutAdminInput, Prisma.LogAdminUncheckedCreateWithoutAdminInput>
}

export type LogAdminCreateManyAdminInputEnvelope = {
  data: Prisma.LogAdminCreateManyAdminInput | Prisma.LogAdminCreateManyAdminInput[]
  skipDuplicates?: boolean
}

export type LogAdminUpsertWithWhereUniqueWithoutAdminInput = {
  where: Prisma.LogAdminWhereUniqueInput
  update: Prisma.XOR<Prisma.LogAdminUpdateWithoutAdminInput, Prisma.LogAdminUncheckedUpdateWithoutAdminInput>
  create: Prisma.XOR<Prisma.LogAdminCreateWithoutAdminInput, Prisma.LogAdminUncheckedCreateWithoutAdminInput>
}

export type LogAdminUpdateWithWhereUniqueWithoutAdminInput = {
  where: Prisma.LogAdminWhereUniqueInput
  data: Prisma.XOR<Prisma.LogAdminUpdateWithoutAdminInput, Prisma.LogAdminUncheckedUpdateWithoutAdminInput>
}

export type LogAdminUpdateManyWithWhereWithoutAdminInput = {
  where: Prisma.LogAdminScalarWhereInput
  data: Prisma.XOR<Prisma.LogAdminUpdateManyMutationInput, Prisma.LogAdminUncheckedUpdateManyWithoutAdminInput>
}

export type LogAdminScalarWhereInput = {
  AND?: Prisma.LogAdminScalarWhereInput | Prisma.LogAdminScalarWhereInput[]
  OR?: Prisma.LogAdminScalarWhereInput[]
  NOT?: Prisma.LogAdminScalarWhereInput | Prisma.LogAdminScalarWhereInput[]
  id?: Prisma.StringFilter<"LogAdmin"> | string
  adminId?: Prisma.StringFilter<"LogAdmin"> | string
  acao?: Prisma.EnumAcaoLogFilter<"LogAdmin"> | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFilter<"LogAdmin"> | $Enums.EntidadeLog
  entidadeId?: Prisma.StringNullableFilter<"LogAdmin"> | string | null
  detalhes?: Prisma.JsonNullableFilter<"LogAdmin">
  criadoEm?: Prisma.DateTimeFilter<"LogAdmin"> | Date | string
}

export type LogAdminCreateManyAdminInput = {
  id?: string
  acao: $Enums.AcaoLog
  entidade: $Enums.EntidadeLog
  entidadeId?: string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Date | string
}

export type LogAdminUpdateWithoutAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogAdminUncheckedUpdateWithoutAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LogAdminUncheckedUpdateManyWithoutAdminInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  acao?: Prisma.EnumAcaoLogFieldUpdateOperationsInput | $Enums.AcaoLog
  entidade?: Prisma.EnumEntidadeLogFieldUpdateOperationsInput | $Enums.EntidadeLog
  entidadeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  detalhes?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  criadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LogAdminSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  adminId?: boolean
  acao?: boolean
  entidade?: boolean
  entidadeId?: boolean
  detalhes?: boolean
  criadoEm?: boolean
  admin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logAdmin"]>

export type LogAdminSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  adminId?: boolean
  acao?: boolean
  entidade?: boolean
  entidadeId?: boolean
  detalhes?: boolean
  criadoEm?: boolean
  admin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logAdmin"]>

export type LogAdminSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  adminId?: boolean
  acao?: boolean
  entidade?: boolean
  entidadeId?: boolean
  detalhes?: boolean
  criadoEm?: boolean
  admin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["logAdmin"]>

export type LogAdminSelectScalar = {
  id?: boolean
  adminId?: boolean
  acao?: boolean
  entidade?: boolean
  entidadeId?: boolean
  detalhes?: boolean
  criadoEm?: boolean
}

export type LogAdminOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "adminId" | "acao" | "entidade" | "entidadeId" | "detalhes" | "criadoEm", ExtArgs["result"]["logAdmin"]>
export type LogAdminInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  admin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LogAdminIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  admin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LogAdminIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  admin?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LogAdminPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LogAdmin"
  objects: {
    admin: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    adminId: string
    acao: $Enums.AcaoLog
    entidade: $Enums.EntidadeLog
    entidadeId: string | null
    detalhes: runtime.JsonValue | null
    criadoEm: Date
  }, ExtArgs["result"]["logAdmin"]>
  composites: {}
}

export type LogAdminGetPayload<S extends boolean | null | undefined | LogAdminDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LogAdminPayload, S>

export type LogAdminCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LogAdminFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LogAdminCountAggregateInputType | true
  }

export interface LogAdminDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LogAdmin'], meta: { name: 'LogAdmin' } }
  /**
   * Find zero or one LogAdmin that matches the filter.
   * @param {LogAdminFindUniqueArgs} args - Arguments to find a LogAdmin
   * @example
   * // Get one LogAdmin
   * const logAdmin = await prisma.logAdmin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LogAdminFindUniqueArgs>(args: Prisma.SelectSubset<T, LogAdminFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LogAdmin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LogAdminFindUniqueOrThrowArgs} args - Arguments to find a LogAdmin
   * @example
   * // Get one LogAdmin
   * const logAdmin = await prisma.logAdmin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LogAdminFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LogAdminFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LogAdmin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminFindFirstArgs} args - Arguments to find a LogAdmin
   * @example
   * // Get one LogAdmin
   * const logAdmin = await prisma.logAdmin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LogAdminFindFirstArgs>(args?: Prisma.SelectSubset<T, LogAdminFindFirstArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LogAdmin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminFindFirstOrThrowArgs} args - Arguments to find a LogAdmin
   * @example
   * // Get one LogAdmin
   * const logAdmin = await prisma.logAdmin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LogAdminFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LogAdminFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LogAdmins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LogAdmins
   * const logAdmins = await prisma.logAdmin.findMany()
   * 
   * // Get first 10 LogAdmins
   * const logAdmins = await prisma.logAdmin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const logAdminWithIdOnly = await prisma.logAdmin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LogAdminFindManyArgs>(args?: Prisma.SelectSubset<T, LogAdminFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LogAdmin.
   * @param {LogAdminCreateArgs} args - Arguments to create a LogAdmin.
   * @example
   * // Create one LogAdmin
   * const LogAdmin = await prisma.logAdmin.create({
   *   data: {
   *     // ... data to create a LogAdmin
   *   }
   * })
   * 
   */
  create<T extends LogAdminCreateArgs>(args: Prisma.SelectSubset<T, LogAdminCreateArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LogAdmins.
   * @param {LogAdminCreateManyArgs} args - Arguments to create many LogAdmins.
   * @example
   * // Create many LogAdmins
   * const logAdmin = await prisma.logAdmin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LogAdminCreateManyArgs>(args?: Prisma.SelectSubset<T, LogAdminCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LogAdmins and returns the data saved in the database.
   * @param {LogAdminCreateManyAndReturnArgs} args - Arguments to create many LogAdmins.
   * @example
   * // Create many LogAdmins
   * const logAdmin = await prisma.logAdmin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LogAdmins and only return the `id`
   * const logAdminWithIdOnly = await prisma.logAdmin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LogAdminCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LogAdminCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LogAdmin.
   * @param {LogAdminDeleteArgs} args - Arguments to delete one LogAdmin.
   * @example
   * // Delete one LogAdmin
   * const LogAdmin = await prisma.logAdmin.delete({
   *   where: {
   *     // ... filter to delete one LogAdmin
   *   }
   * })
   * 
   */
  delete<T extends LogAdminDeleteArgs>(args: Prisma.SelectSubset<T, LogAdminDeleteArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LogAdmin.
   * @param {LogAdminUpdateArgs} args - Arguments to update one LogAdmin.
   * @example
   * // Update one LogAdmin
   * const logAdmin = await prisma.logAdmin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LogAdminUpdateArgs>(args: Prisma.SelectSubset<T, LogAdminUpdateArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LogAdmins.
   * @param {LogAdminDeleteManyArgs} args - Arguments to filter LogAdmins to delete.
   * @example
   * // Delete a few LogAdmins
   * const { count } = await prisma.logAdmin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LogAdminDeleteManyArgs>(args?: Prisma.SelectSubset<T, LogAdminDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LogAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LogAdmins
   * const logAdmin = await prisma.logAdmin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LogAdminUpdateManyArgs>(args: Prisma.SelectSubset<T, LogAdminUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LogAdmins and returns the data updated in the database.
   * @param {LogAdminUpdateManyAndReturnArgs} args - Arguments to update many LogAdmins.
   * @example
   * // Update many LogAdmins
   * const logAdmin = await prisma.logAdmin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LogAdmins and only return the `id`
   * const logAdminWithIdOnly = await prisma.logAdmin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LogAdminUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LogAdminUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LogAdmin.
   * @param {LogAdminUpsertArgs} args - Arguments to update or create a LogAdmin.
   * @example
   * // Update or create a LogAdmin
   * const logAdmin = await prisma.logAdmin.upsert({
   *   create: {
   *     // ... data to create a LogAdmin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LogAdmin we want to update
   *   }
   * })
   */
  upsert<T extends LogAdminUpsertArgs>(args: Prisma.SelectSubset<T, LogAdminUpsertArgs<ExtArgs>>): Prisma.Prisma__LogAdminClient<runtime.Types.Result.GetResult<Prisma.$LogAdminPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LogAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminCountArgs} args - Arguments to filter LogAdmins to count.
   * @example
   * // Count the number of LogAdmins
   * const count = await prisma.logAdmin.count({
   *   where: {
   *     // ... the filter for the LogAdmins we want to count
   *   }
   * })
  **/
  count<T extends LogAdminCountArgs>(
    args?: Prisma.Subset<T, LogAdminCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LogAdminCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LogAdmin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LogAdminAggregateArgs>(args: Prisma.Subset<T, LogAdminAggregateArgs>): Prisma.PrismaPromise<GetLogAdminAggregateType<T>>

  /**
   * Group by LogAdmin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LogAdminGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LogAdminGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LogAdminGroupByArgs['orderBy'] }
      : { orderBy?: LogAdminGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LogAdminGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLogAdminGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LogAdmin model
 */
readonly fields: LogAdminFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LogAdmin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LogAdminClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  admin<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LogAdmin model
 */
export interface LogAdminFieldRefs {
  readonly id: Prisma.FieldRef<"LogAdmin", 'String'>
  readonly adminId: Prisma.FieldRef<"LogAdmin", 'String'>
  readonly acao: Prisma.FieldRef<"LogAdmin", 'AcaoLog'>
  readonly entidade: Prisma.FieldRef<"LogAdmin", 'EntidadeLog'>
  readonly entidadeId: Prisma.FieldRef<"LogAdmin", 'String'>
  readonly detalhes: Prisma.FieldRef<"LogAdmin", 'Json'>
  readonly criadoEm: Prisma.FieldRef<"LogAdmin", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LogAdmin findUnique
 */
export type LogAdminFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * Filter, which LogAdmin to fetch.
   */
  where: Prisma.LogAdminWhereUniqueInput
}

/**
 * LogAdmin findUniqueOrThrow
 */
export type LogAdminFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * Filter, which LogAdmin to fetch.
   */
  where: Prisma.LogAdminWhereUniqueInput
}

/**
 * LogAdmin findFirst
 */
export type LogAdminFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * Filter, which LogAdmin to fetch.
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogAdmins to fetch.
   */
  orderBy?: Prisma.LogAdminOrderByWithRelationInput | Prisma.LogAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LogAdmins.
   */
  cursor?: Prisma.LogAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogAdmins.
   */
  distinct?: Prisma.LogAdminScalarFieldEnum | Prisma.LogAdminScalarFieldEnum[]
}

/**
 * LogAdmin findFirstOrThrow
 */
export type LogAdminFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * Filter, which LogAdmin to fetch.
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogAdmins to fetch.
   */
  orderBy?: Prisma.LogAdminOrderByWithRelationInput | Prisma.LogAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LogAdmins.
   */
  cursor?: Prisma.LogAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogAdmins.
   */
  distinct?: Prisma.LogAdminScalarFieldEnum | Prisma.LogAdminScalarFieldEnum[]
}

/**
 * LogAdmin findMany
 */
export type LogAdminFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * Filter, which LogAdmins to fetch.
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LogAdmins to fetch.
   */
  orderBy?: Prisma.LogAdminOrderByWithRelationInput | Prisma.LogAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LogAdmins.
   */
  cursor?: Prisma.LogAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LogAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LogAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LogAdmins.
   */
  distinct?: Prisma.LogAdminScalarFieldEnum | Prisma.LogAdminScalarFieldEnum[]
}

/**
 * LogAdmin create
 */
export type LogAdminCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * The data needed to create a LogAdmin.
   */
  data: Prisma.XOR<Prisma.LogAdminCreateInput, Prisma.LogAdminUncheckedCreateInput>
}

/**
 * LogAdmin createMany
 */
export type LogAdminCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LogAdmins.
   */
  data: Prisma.LogAdminCreateManyInput | Prisma.LogAdminCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LogAdmin createManyAndReturn
 */
export type LogAdminCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * The data used to create many LogAdmins.
   */
  data: Prisma.LogAdminCreateManyInput | Prisma.LogAdminCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LogAdmin update
 */
export type LogAdminUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * The data needed to update a LogAdmin.
   */
  data: Prisma.XOR<Prisma.LogAdminUpdateInput, Prisma.LogAdminUncheckedUpdateInput>
  /**
   * Choose, which LogAdmin to update.
   */
  where: Prisma.LogAdminWhereUniqueInput
}

/**
 * LogAdmin updateMany
 */
export type LogAdminUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LogAdmins.
   */
  data: Prisma.XOR<Prisma.LogAdminUpdateManyMutationInput, Prisma.LogAdminUncheckedUpdateManyInput>
  /**
   * Filter which LogAdmins to update
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * Limit how many LogAdmins to update.
   */
  limit?: number
}

/**
 * LogAdmin updateManyAndReturn
 */
export type LogAdminUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * The data used to update LogAdmins.
   */
  data: Prisma.XOR<Prisma.LogAdminUpdateManyMutationInput, Prisma.LogAdminUncheckedUpdateManyInput>
  /**
   * Filter which LogAdmins to update
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * Limit how many LogAdmins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LogAdmin upsert
 */
export type LogAdminUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * The filter to search for the LogAdmin to update in case it exists.
   */
  where: Prisma.LogAdminWhereUniqueInput
  /**
   * In case the LogAdmin found by the `where` argument doesn't exist, create a new LogAdmin with this data.
   */
  create: Prisma.XOR<Prisma.LogAdminCreateInput, Prisma.LogAdminUncheckedCreateInput>
  /**
   * In case the LogAdmin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LogAdminUpdateInput, Prisma.LogAdminUncheckedUpdateInput>
}

/**
 * LogAdmin delete
 */
export type LogAdminDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
  /**
   * Filter which LogAdmin to delete.
   */
  where: Prisma.LogAdminWhereUniqueInput
}

/**
 * LogAdmin deleteMany
 */
export type LogAdminDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LogAdmins to delete
   */
  where?: Prisma.LogAdminWhereInput
  /**
   * Limit how many LogAdmins to delete.
   */
  limit?: number
}

/**
 * LogAdmin without action
 */
export type LogAdminDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LogAdmin
   */
  select?: Prisma.LogAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LogAdmin
   */
  omit?: Prisma.LogAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LogAdminInclude<ExtArgs> | null
}
