
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Noticia` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Noticia
 * 
 */
export type NoticiaModel = runtime.Types.Result.DefaultSelection<Prisma.$NoticiaPayload>

export type AggregateNoticia = {
  _count: NoticiaCountAggregateOutputType | null
  _avg: NoticiaAvgAggregateOutputType | null
  _sum: NoticiaSumAggregateOutputType | null
  _min: NoticiaMinAggregateOutputType | null
  _max: NoticiaMaxAggregateOutputType | null
}

export type NoticiaAvgAggregateOutputType = {
  tempoDeLeituraMin: number | null
}

export type NoticiaSumAggregateOutputType = {
  tempoDeLeituraMin: number | null
}

export type NoticiaMinAggregateOutputType = {
  id: string | null
  titulo: string | null
  subTitulo: string | null
  corpoDaNoticia: string | null
  imagemCapa: string | null
  tempoDeLeituraMin: number | null
  autor: string | null
  grupoId: string | null
  publicadoEm: Date | null
  atualizadoEm: Date | null
}

export type NoticiaMaxAggregateOutputType = {
  id: string | null
  titulo: string | null
  subTitulo: string | null
  corpoDaNoticia: string | null
  imagemCapa: string | null
  tempoDeLeituraMin: number | null
  autor: string | null
  grupoId: string | null
  publicadoEm: Date | null
  atualizadoEm: Date | null
}

export type NoticiaCountAggregateOutputType = {
  id: number
  titulo: number
  subTitulo: number
  corpoDaNoticia: number
  imagemCapa: number
  tempoDeLeituraMin: number
  autor: number
  grupoId: number
  publicadoEm: number
  atualizadoEm: number
  _all: number
}


export type NoticiaAvgAggregateInputType = {
  tempoDeLeituraMin?: true
}

export type NoticiaSumAggregateInputType = {
  tempoDeLeituraMin?: true
}

export type NoticiaMinAggregateInputType = {
  id?: true
  titulo?: true
  subTitulo?: true
  corpoDaNoticia?: true
  imagemCapa?: true
  tempoDeLeituraMin?: true
  autor?: true
  grupoId?: true
  publicadoEm?: true
  atualizadoEm?: true
}

export type NoticiaMaxAggregateInputType = {
  id?: true
  titulo?: true
  subTitulo?: true
  corpoDaNoticia?: true
  imagemCapa?: true
  tempoDeLeituraMin?: true
  autor?: true
  grupoId?: true
  publicadoEm?: true
  atualizadoEm?: true
}

export type NoticiaCountAggregateInputType = {
  id?: true
  titulo?: true
  subTitulo?: true
  corpoDaNoticia?: true
  imagemCapa?: true
  tempoDeLeituraMin?: true
  autor?: true
  grupoId?: true
  publicadoEm?: true
  atualizadoEm?: true
  _all?: true
}

export type NoticiaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Noticia to aggregate.
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Noticias to fetch.
   */
  orderBy?: Prisma.NoticiaOrderByWithRelationInput | Prisma.NoticiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NoticiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Noticias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Noticias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Noticias
  **/
  _count?: true | NoticiaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NoticiaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NoticiaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NoticiaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NoticiaMaxAggregateInputType
}

export type GetNoticiaAggregateType<T extends NoticiaAggregateArgs> = {
      [P in keyof T & keyof AggregateNoticia]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNoticia[P]>
    : Prisma.GetScalarType<T[P], AggregateNoticia[P]>
}




export type NoticiaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NoticiaWhereInput
  orderBy?: Prisma.NoticiaOrderByWithAggregationInput | Prisma.NoticiaOrderByWithAggregationInput[]
  by: Prisma.NoticiaScalarFieldEnum[] | Prisma.NoticiaScalarFieldEnum
  having?: Prisma.NoticiaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NoticiaCountAggregateInputType | true
  _avg?: NoticiaAvgAggregateInputType
  _sum?: NoticiaSumAggregateInputType
  _min?: NoticiaMinAggregateInputType
  _max?: NoticiaMaxAggregateInputType
}

export type NoticiaGroupByOutputType = {
  id: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  grupoId: string | null
  publicadoEm: Date
  atualizadoEm: Date
  _count: NoticiaCountAggregateOutputType | null
  _avg: NoticiaAvgAggregateOutputType | null
  _sum: NoticiaSumAggregateOutputType | null
  _min: NoticiaMinAggregateOutputType | null
  _max: NoticiaMaxAggregateOutputType | null
}

export type GetNoticiaGroupByPayload<T extends NoticiaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NoticiaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NoticiaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NoticiaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NoticiaGroupByOutputType[P]>
      }
    >
  >



export type NoticiaWhereInput = {
  AND?: Prisma.NoticiaWhereInput | Prisma.NoticiaWhereInput[]
  OR?: Prisma.NoticiaWhereInput[]
  NOT?: Prisma.NoticiaWhereInput | Prisma.NoticiaWhereInput[]
  id?: Prisma.StringFilter<"Noticia"> | string
  titulo?: Prisma.StringFilter<"Noticia"> | string
  subTitulo?: Prisma.StringFilter<"Noticia"> | string
  corpoDaNoticia?: Prisma.StringFilter<"Noticia"> | string
  imagemCapa?: Prisma.StringFilter<"Noticia"> | string
  tempoDeLeituraMin?: Prisma.IntFilter<"Noticia"> | number
  autor?: Prisma.StringFilter<"Noticia"> | string
  grupoId?: Prisma.StringNullableFilter<"Noticia"> | string | null
  publicadoEm?: Prisma.DateTimeFilter<"Noticia"> | Date | string
  atualizadoEm?: Prisma.DateTimeFilter<"Noticia"> | Date | string
  grupo?: Prisma.XOR<Prisma.GrupoNullableScalarRelationFilter, Prisma.GrupoWhereInput> | null
}

export type NoticiaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  subTitulo?: Prisma.SortOrder
  corpoDaNoticia?: Prisma.SortOrder
  imagemCapa?: Prisma.SortOrder
  tempoDeLeituraMin?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  grupoId?: Prisma.SortOrderInput | Prisma.SortOrder
  publicadoEm?: Prisma.SortOrder
  atualizadoEm?: Prisma.SortOrder
  grupo?: Prisma.GrupoOrderByWithRelationInput
}

export type NoticiaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NoticiaWhereInput | Prisma.NoticiaWhereInput[]
  OR?: Prisma.NoticiaWhereInput[]
  NOT?: Prisma.NoticiaWhereInput | Prisma.NoticiaWhereInput[]
  titulo?: Prisma.StringFilter<"Noticia"> | string
  subTitulo?: Prisma.StringFilter<"Noticia"> | string
  corpoDaNoticia?: Prisma.StringFilter<"Noticia"> | string
  imagemCapa?: Prisma.StringFilter<"Noticia"> | string
  tempoDeLeituraMin?: Prisma.IntFilter<"Noticia"> | number
  autor?: Prisma.StringFilter<"Noticia"> | string
  grupoId?: Prisma.StringNullableFilter<"Noticia"> | string | null
  publicadoEm?: Prisma.DateTimeFilter<"Noticia"> | Date | string
  atualizadoEm?: Prisma.DateTimeFilter<"Noticia"> | Date | string
  grupo?: Prisma.XOR<Prisma.GrupoNullableScalarRelationFilter, Prisma.GrupoWhereInput> | null
}, "id">

export type NoticiaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  subTitulo?: Prisma.SortOrder
  corpoDaNoticia?: Prisma.SortOrder
  imagemCapa?: Prisma.SortOrder
  tempoDeLeituraMin?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  grupoId?: Prisma.SortOrderInput | Prisma.SortOrder
  publicadoEm?: Prisma.SortOrder
  atualizadoEm?: Prisma.SortOrder
  _count?: Prisma.NoticiaCountOrderByAggregateInput
  _avg?: Prisma.NoticiaAvgOrderByAggregateInput
  _max?: Prisma.NoticiaMaxOrderByAggregateInput
  _min?: Prisma.NoticiaMinOrderByAggregateInput
  _sum?: Prisma.NoticiaSumOrderByAggregateInput
}

export type NoticiaScalarWhereWithAggregatesInput = {
  AND?: Prisma.NoticiaScalarWhereWithAggregatesInput | Prisma.NoticiaScalarWhereWithAggregatesInput[]
  OR?: Prisma.NoticiaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NoticiaScalarWhereWithAggregatesInput | Prisma.NoticiaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Noticia"> | string
  titulo?: Prisma.StringWithAggregatesFilter<"Noticia"> | string
  subTitulo?: Prisma.StringWithAggregatesFilter<"Noticia"> | string
  corpoDaNoticia?: Prisma.StringWithAggregatesFilter<"Noticia"> | string
  imagemCapa?: Prisma.StringWithAggregatesFilter<"Noticia"> | string
  tempoDeLeituraMin?: Prisma.IntWithAggregatesFilter<"Noticia"> | number
  autor?: Prisma.StringWithAggregatesFilter<"Noticia"> | string
  grupoId?: Prisma.StringNullableWithAggregatesFilter<"Noticia"> | string | null
  publicadoEm?: Prisma.DateTimeWithAggregatesFilter<"Noticia"> | Date | string
  atualizadoEm?: Prisma.DateTimeWithAggregatesFilter<"Noticia"> | Date | string
}

export type NoticiaCreateInput = {
  id?: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  publicadoEm?: Date | string
  atualizadoEm?: Date | string
  grupo?: Prisma.GrupoCreateNestedOneWithoutNoticiasInput
}

export type NoticiaUncheckedCreateInput = {
  id?: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  grupoId?: string | null
  publicadoEm?: Date | string
  atualizadoEm?: Date | string
}

export type NoticiaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grupo?: Prisma.GrupoUpdateOneWithoutNoticiasNestedInput
}

export type NoticiaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  grupoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticiaCreateManyInput = {
  id?: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  grupoId?: string | null
  publicadoEm?: Date | string
  atualizadoEm?: Date | string
}

export type NoticiaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticiaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  grupoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticiaListRelationFilter = {
  every?: Prisma.NoticiaWhereInput
  some?: Prisma.NoticiaWhereInput
  none?: Prisma.NoticiaWhereInput
}

export type NoticiaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NoticiaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  subTitulo?: Prisma.SortOrder
  corpoDaNoticia?: Prisma.SortOrder
  imagemCapa?: Prisma.SortOrder
  tempoDeLeituraMin?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  publicadoEm?: Prisma.SortOrder
  atualizadoEm?: Prisma.SortOrder
}

export type NoticiaAvgOrderByAggregateInput = {
  tempoDeLeituraMin?: Prisma.SortOrder
}

export type NoticiaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  subTitulo?: Prisma.SortOrder
  corpoDaNoticia?: Prisma.SortOrder
  imagemCapa?: Prisma.SortOrder
  tempoDeLeituraMin?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  publicadoEm?: Prisma.SortOrder
  atualizadoEm?: Prisma.SortOrder
}

export type NoticiaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  subTitulo?: Prisma.SortOrder
  corpoDaNoticia?: Prisma.SortOrder
  imagemCapa?: Prisma.SortOrder
  tempoDeLeituraMin?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  publicadoEm?: Prisma.SortOrder
  atualizadoEm?: Prisma.SortOrder
}

export type NoticiaSumOrderByAggregateInput = {
  tempoDeLeituraMin?: Prisma.SortOrder
}

export type NoticiaCreateNestedManyWithoutGrupoInput = {
  create?: Prisma.XOR<Prisma.NoticiaCreateWithoutGrupoInput, Prisma.NoticiaUncheckedCreateWithoutGrupoInput> | Prisma.NoticiaCreateWithoutGrupoInput[] | Prisma.NoticiaUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.NoticiaCreateOrConnectWithoutGrupoInput | Prisma.NoticiaCreateOrConnectWithoutGrupoInput[]
  createMany?: Prisma.NoticiaCreateManyGrupoInputEnvelope
  connect?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
}

export type NoticiaUncheckedCreateNestedManyWithoutGrupoInput = {
  create?: Prisma.XOR<Prisma.NoticiaCreateWithoutGrupoInput, Prisma.NoticiaUncheckedCreateWithoutGrupoInput> | Prisma.NoticiaCreateWithoutGrupoInput[] | Prisma.NoticiaUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.NoticiaCreateOrConnectWithoutGrupoInput | Prisma.NoticiaCreateOrConnectWithoutGrupoInput[]
  createMany?: Prisma.NoticiaCreateManyGrupoInputEnvelope
  connect?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
}

export type NoticiaUpdateManyWithoutGrupoNestedInput = {
  create?: Prisma.XOR<Prisma.NoticiaCreateWithoutGrupoInput, Prisma.NoticiaUncheckedCreateWithoutGrupoInput> | Prisma.NoticiaCreateWithoutGrupoInput[] | Prisma.NoticiaUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.NoticiaCreateOrConnectWithoutGrupoInput | Prisma.NoticiaCreateOrConnectWithoutGrupoInput[]
  upsert?: Prisma.NoticiaUpsertWithWhereUniqueWithoutGrupoInput | Prisma.NoticiaUpsertWithWhereUniqueWithoutGrupoInput[]
  createMany?: Prisma.NoticiaCreateManyGrupoInputEnvelope
  set?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  disconnect?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  delete?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  connect?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  update?: Prisma.NoticiaUpdateWithWhereUniqueWithoutGrupoInput | Prisma.NoticiaUpdateWithWhereUniqueWithoutGrupoInput[]
  updateMany?: Prisma.NoticiaUpdateManyWithWhereWithoutGrupoInput | Prisma.NoticiaUpdateManyWithWhereWithoutGrupoInput[]
  deleteMany?: Prisma.NoticiaScalarWhereInput | Prisma.NoticiaScalarWhereInput[]
}

export type NoticiaUncheckedUpdateManyWithoutGrupoNestedInput = {
  create?: Prisma.XOR<Prisma.NoticiaCreateWithoutGrupoInput, Prisma.NoticiaUncheckedCreateWithoutGrupoInput> | Prisma.NoticiaCreateWithoutGrupoInput[] | Prisma.NoticiaUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.NoticiaCreateOrConnectWithoutGrupoInput | Prisma.NoticiaCreateOrConnectWithoutGrupoInput[]
  upsert?: Prisma.NoticiaUpsertWithWhereUniqueWithoutGrupoInput | Prisma.NoticiaUpsertWithWhereUniqueWithoutGrupoInput[]
  createMany?: Prisma.NoticiaCreateManyGrupoInputEnvelope
  set?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  disconnect?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  delete?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  connect?: Prisma.NoticiaWhereUniqueInput | Prisma.NoticiaWhereUniqueInput[]
  update?: Prisma.NoticiaUpdateWithWhereUniqueWithoutGrupoInput | Prisma.NoticiaUpdateWithWhereUniqueWithoutGrupoInput[]
  updateMany?: Prisma.NoticiaUpdateManyWithWhereWithoutGrupoInput | Prisma.NoticiaUpdateManyWithWhereWithoutGrupoInput[]
  deleteMany?: Prisma.NoticiaScalarWhereInput | Prisma.NoticiaScalarWhereInput[]
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NoticiaCreateWithoutGrupoInput = {
  id?: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  publicadoEm?: Date | string
  atualizadoEm?: Date | string
}

export type NoticiaUncheckedCreateWithoutGrupoInput = {
  id?: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  publicadoEm?: Date | string
  atualizadoEm?: Date | string
}

export type NoticiaCreateOrConnectWithoutGrupoInput = {
  where: Prisma.NoticiaWhereUniqueInput
  create: Prisma.XOR<Prisma.NoticiaCreateWithoutGrupoInput, Prisma.NoticiaUncheckedCreateWithoutGrupoInput>
}

export type NoticiaCreateManyGrupoInputEnvelope = {
  data: Prisma.NoticiaCreateManyGrupoInput | Prisma.NoticiaCreateManyGrupoInput[]
  skipDuplicates?: boolean
}

export type NoticiaUpsertWithWhereUniqueWithoutGrupoInput = {
  where: Prisma.NoticiaWhereUniqueInput
  update: Prisma.XOR<Prisma.NoticiaUpdateWithoutGrupoInput, Prisma.NoticiaUncheckedUpdateWithoutGrupoInput>
  create: Prisma.XOR<Prisma.NoticiaCreateWithoutGrupoInput, Prisma.NoticiaUncheckedCreateWithoutGrupoInput>
}

export type NoticiaUpdateWithWhereUniqueWithoutGrupoInput = {
  where: Prisma.NoticiaWhereUniqueInput
  data: Prisma.XOR<Prisma.NoticiaUpdateWithoutGrupoInput, Prisma.NoticiaUncheckedUpdateWithoutGrupoInput>
}

export type NoticiaUpdateManyWithWhereWithoutGrupoInput = {
  where: Prisma.NoticiaScalarWhereInput
  data: Prisma.XOR<Prisma.NoticiaUpdateManyMutationInput, Prisma.NoticiaUncheckedUpdateManyWithoutGrupoInput>
}

export type NoticiaScalarWhereInput = {
  AND?: Prisma.NoticiaScalarWhereInput | Prisma.NoticiaScalarWhereInput[]
  OR?: Prisma.NoticiaScalarWhereInput[]
  NOT?: Prisma.NoticiaScalarWhereInput | Prisma.NoticiaScalarWhereInput[]
  id?: Prisma.StringFilter<"Noticia"> | string
  titulo?: Prisma.StringFilter<"Noticia"> | string
  subTitulo?: Prisma.StringFilter<"Noticia"> | string
  corpoDaNoticia?: Prisma.StringFilter<"Noticia"> | string
  imagemCapa?: Prisma.StringFilter<"Noticia"> | string
  tempoDeLeituraMin?: Prisma.IntFilter<"Noticia"> | number
  autor?: Prisma.StringFilter<"Noticia"> | string
  grupoId?: Prisma.StringNullableFilter<"Noticia"> | string | null
  publicadoEm?: Prisma.DateTimeFilter<"Noticia"> | Date | string
  atualizadoEm?: Prisma.DateTimeFilter<"Noticia"> | Date | string
}

export type NoticiaCreateManyGrupoInput = {
  id?: string
  titulo: string
  subTitulo: string
  corpoDaNoticia: string
  imagemCapa: string
  tempoDeLeituraMin: number
  autor: string
  publicadoEm?: Date | string
  atualizadoEm?: Date | string
}

export type NoticiaUpdateWithoutGrupoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticiaUncheckedUpdateWithoutGrupoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NoticiaUncheckedUpdateManyWithoutGrupoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  subTitulo?: Prisma.StringFieldUpdateOperationsInput | string
  corpoDaNoticia?: Prisma.StringFieldUpdateOperationsInput | string
  imagemCapa?: Prisma.StringFieldUpdateOperationsInput | string
  tempoDeLeituraMin?: Prisma.IntFieldUpdateOperationsInput | number
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  publicadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atualizadoEm?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NoticiaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  subTitulo?: boolean
  corpoDaNoticia?: boolean
  imagemCapa?: boolean
  tempoDeLeituraMin?: boolean
  autor?: boolean
  grupoId?: boolean
  publicadoEm?: boolean
  atualizadoEm?: boolean
  grupo?: boolean | Prisma.Noticia$grupoArgs<ExtArgs>
}, ExtArgs["result"]["noticia"]>

export type NoticiaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  subTitulo?: boolean
  corpoDaNoticia?: boolean
  imagemCapa?: boolean
  tempoDeLeituraMin?: boolean
  autor?: boolean
  grupoId?: boolean
  publicadoEm?: boolean
  atualizadoEm?: boolean
  grupo?: boolean | Prisma.Noticia$grupoArgs<ExtArgs>
}, ExtArgs["result"]["noticia"]>

export type NoticiaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titulo?: boolean
  subTitulo?: boolean
  corpoDaNoticia?: boolean
  imagemCapa?: boolean
  tempoDeLeituraMin?: boolean
  autor?: boolean
  grupoId?: boolean
  publicadoEm?: boolean
  atualizadoEm?: boolean
  grupo?: boolean | Prisma.Noticia$grupoArgs<ExtArgs>
}, ExtArgs["result"]["noticia"]>

export type NoticiaSelectScalar = {
  id?: boolean
  titulo?: boolean
  subTitulo?: boolean
  corpoDaNoticia?: boolean
  imagemCapa?: boolean
  tempoDeLeituraMin?: boolean
  autor?: boolean
  grupoId?: boolean
  publicadoEm?: boolean
  atualizadoEm?: boolean
}

export type NoticiaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "titulo" | "subTitulo" | "corpoDaNoticia" | "imagemCapa" | "tempoDeLeituraMin" | "autor" | "grupoId" | "publicadoEm" | "atualizadoEm", ExtArgs["result"]["noticia"]>
export type NoticiaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.Noticia$grupoArgs<ExtArgs>
}
export type NoticiaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.Noticia$grupoArgs<ExtArgs>
}
export type NoticiaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.Noticia$grupoArgs<ExtArgs>
}

export type $NoticiaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Noticia"
  objects: {
    grupo: Prisma.$GrupoPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    titulo: string
    subTitulo: string
    corpoDaNoticia: string
    imagemCapa: string
    tempoDeLeituraMin: number
    autor: string
    grupoId: string | null
    publicadoEm: Date
    atualizadoEm: Date
  }, ExtArgs["result"]["noticia"]>
  composites: {}
}

export type NoticiaGetPayload<S extends boolean | null | undefined | NoticiaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NoticiaPayload, S>

export type NoticiaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NoticiaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NoticiaCountAggregateInputType | true
  }

export interface NoticiaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Noticia'], meta: { name: 'Noticia' } }
  /**
   * Find zero or one Noticia that matches the filter.
   * @param {NoticiaFindUniqueArgs} args - Arguments to find a Noticia
   * @example
   * // Get one Noticia
   * const noticia = await prisma.noticia.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NoticiaFindUniqueArgs>(args: Prisma.SelectSubset<T, NoticiaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Noticia that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NoticiaFindUniqueOrThrowArgs} args - Arguments to find a Noticia
   * @example
   * // Get one Noticia
   * const noticia = await prisma.noticia.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NoticiaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NoticiaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Noticia that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaFindFirstArgs} args - Arguments to find a Noticia
   * @example
   * // Get one Noticia
   * const noticia = await prisma.noticia.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NoticiaFindFirstArgs>(args?: Prisma.SelectSubset<T, NoticiaFindFirstArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Noticia that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaFindFirstOrThrowArgs} args - Arguments to find a Noticia
   * @example
   * // Get one Noticia
   * const noticia = await prisma.noticia.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NoticiaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NoticiaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Noticias that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Noticias
   * const noticias = await prisma.noticia.findMany()
   * 
   * // Get first 10 Noticias
   * const noticias = await prisma.noticia.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const noticiaWithIdOnly = await prisma.noticia.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NoticiaFindManyArgs>(args?: Prisma.SelectSubset<T, NoticiaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Noticia.
   * @param {NoticiaCreateArgs} args - Arguments to create a Noticia.
   * @example
   * // Create one Noticia
   * const Noticia = await prisma.noticia.create({
   *   data: {
   *     // ... data to create a Noticia
   *   }
   * })
   * 
   */
  create<T extends NoticiaCreateArgs>(args: Prisma.SelectSubset<T, NoticiaCreateArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Noticias.
   * @param {NoticiaCreateManyArgs} args - Arguments to create many Noticias.
   * @example
   * // Create many Noticias
   * const noticia = await prisma.noticia.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NoticiaCreateManyArgs>(args?: Prisma.SelectSubset<T, NoticiaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Noticias and returns the data saved in the database.
   * @param {NoticiaCreateManyAndReturnArgs} args - Arguments to create many Noticias.
   * @example
   * // Create many Noticias
   * const noticia = await prisma.noticia.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Noticias and only return the `id`
   * const noticiaWithIdOnly = await prisma.noticia.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NoticiaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NoticiaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Noticia.
   * @param {NoticiaDeleteArgs} args - Arguments to delete one Noticia.
   * @example
   * // Delete one Noticia
   * const Noticia = await prisma.noticia.delete({
   *   where: {
   *     // ... filter to delete one Noticia
   *   }
   * })
   * 
   */
  delete<T extends NoticiaDeleteArgs>(args: Prisma.SelectSubset<T, NoticiaDeleteArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Noticia.
   * @param {NoticiaUpdateArgs} args - Arguments to update one Noticia.
   * @example
   * // Update one Noticia
   * const noticia = await prisma.noticia.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NoticiaUpdateArgs>(args: Prisma.SelectSubset<T, NoticiaUpdateArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Noticias.
   * @param {NoticiaDeleteManyArgs} args - Arguments to filter Noticias to delete.
   * @example
   * // Delete a few Noticias
   * const { count } = await prisma.noticia.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NoticiaDeleteManyArgs>(args?: Prisma.SelectSubset<T, NoticiaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Noticias.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Noticias
   * const noticia = await prisma.noticia.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NoticiaUpdateManyArgs>(args: Prisma.SelectSubset<T, NoticiaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Noticias and returns the data updated in the database.
   * @param {NoticiaUpdateManyAndReturnArgs} args - Arguments to update many Noticias.
   * @example
   * // Update many Noticias
   * const noticia = await prisma.noticia.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Noticias and only return the `id`
   * const noticiaWithIdOnly = await prisma.noticia.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NoticiaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NoticiaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Noticia.
   * @param {NoticiaUpsertArgs} args - Arguments to update or create a Noticia.
   * @example
   * // Update or create a Noticia
   * const noticia = await prisma.noticia.upsert({
   *   create: {
   *     // ... data to create a Noticia
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Noticia we want to update
   *   }
   * })
   */
  upsert<T extends NoticiaUpsertArgs>(args: Prisma.SelectSubset<T, NoticiaUpsertArgs<ExtArgs>>): Prisma.Prisma__NoticiaClient<runtime.Types.Result.GetResult<Prisma.$NoticiaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Noticias.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaCountArgs} args - Arguments to filter Noticias to count.
   * @example
   * // Count the number of Noticias
   * const count = await prisma.noticia.count({
   *   where: {
   *     // ... the filter for the Noticias we want to count
   *   }
   * })
  **/
  count<T extends NoticiaCountArgs>(
    args?: Prisma.Subset<T, NoticiaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NoticiaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Noticia.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NoticiaAggregateArgs>(args: Prisma.Subset<T, NoticiaAggregateArgs>): Prisma.PrismaPromise<GetNoticiaAggregateType<T>>

  /**
   * Group by Noticia.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NoticiaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NoticiaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NoticiaGroupByArgs['orderBy'] }
      : { orderBy?: NoticiaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NoticiaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNoticiaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Noticia model
 */
readonly fields: NoticiaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Noticia.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NoticiaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  grupo<T extends Prisma.Noticia$grupoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Noticia$grupoArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Noticia model
 */
export interface NoticiaFieldRefs {
  readonly id: Prisma.FieldRef<"Noticia", 'String'>
  readonly titulo: Prisma.FieldRef<"Noticia", 'String'>
  readonly subTitulo: Prisma.FieldRef<"Noticia", 'String'>
  readonly corpoDaNoticia: Prisma.FieldRef<"Noticia", 'String'>
  readonly imagemCapa: Prisma.FieldRef<"Noticia", 'String'>
  readonly tempoDeLeituraMin: Prisma.FieldRef<"Noticia", 'Int'>
  readonly autor: Prisma.FieldRef<"Noticia", 'String'>
  readonly grupoId: Prisma.FieldRef<"Noticia", 'String'>
  readonly publicadoEm: Prisma.FieldRef<"Noticia", 'DateTime'>
  readonly atualizadoEm: Prisma.FieldRef<"Noticia", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Noticia findUnique
 */
export type NoticiaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * Filter, which Noticia to fetch.
   */
  where: Prisma.NoticiaWhereUniqueInput
}

/**
 * Noticia findUniqueOrThrow
 */
export type NoticiaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * Filter, which Noticia to fetch.
   */
  where: Prisma.NoticiaWhereUniqueInput
}

/**
 * Noticia findFirst
 */
export type NoticiaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * Filter, which Noticia to fetch.
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Noticias to fetch.
   */
  orderBy?: Prisma.NoticiaOrderByWithRelationInput | Prisma.NoticiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Noticias.
   */
  cursor?: Prisma.NoticiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Noticias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Noticias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Noticias.
   */
  distinct?: Prisma.NoticiaScalarFieldEnum | Prisma.NoticiaScalarFieldEnum[]
}

/**
 * Noticia findFirstOrThrow
 */
export type NoticiaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * Filter, which Noticia to fetch.
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Noticias to fetch.
   */
  orderBy?: Prisma.NoticiaOrderByWithRelationInput | Prisma.NoticiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Noticias.
   */
  cursor?: Prisma.NoticiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Noticias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Noticias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Noticias.
   */
  distinct?: Prisma.NoticiaScalarFieldEnum | Prisma.NoticiaScalarFieldEnum[]
}

/**
 * Noticia findMany
 */
export type NoticiaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * Filter, which Noticias to fetch.
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Noticias to fetch.
   */
  orderBy?: Prisma.NoticiaOrderByWithRelationInput | Prisma.NoticiaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Noticias.
   */
  cursor?: Prisma.NoticiaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Noticias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Noticias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Noticias.
   */
  distinct?: Prisma.NoticiaScalarFieldEnum | Prisma.NoticiaScalarFieldEnum[]
}

/**
 * Noticia create
 */
export type NoticiaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * The data needed to create a Noticia.
   */
  data: Prisma.XOR<Prisma.NoticiaCreateInput, Prisma.NoticiaUncheckedCreateInput>
}

/**
 * Noticia createMany
 */
export type NoticiaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Noticias.
   */
  data: Prisma.NoticiaCreateManyInput | Prisma.NoticiaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Noticia createManyAndReturn
 */
export type NoticiaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * The data used to create many Noticias.
   */
  data: Prisma.NoticiaCreateManyInput | Prisma.NoticiaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Noticia update
 */
export type NoticiaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * The data needed to update a Noticia.
   */
  data: Prisma.XOR<Prisma.NoticiaUpdateInput, Prisma.NoticiaUncheckedUpdateInput>
  /**
   * Choose, which Noticia to update.
   */
  where: Prisma.NoticiaWhereUniqueInput
}

/**
 * Noticia updateMany
 */
export type NoticiaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Noticias.
   */
  data: Prisma.XOR<Prisma.NoticiaUpdateManyMutationInput, Prisma.NoticiaUncheckedUpdateManyInput>
  /**
   * Filter which Noticias to update
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * Limit how many Noticias to update.
   */
  limit?: number
}

/**
 * Noticia updateManyAndReturn
 */
export type NoticiaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * The data used to update Noticias.
   */
  data: Prisma.XOR<Prisma.NoticiaUpdateManyMutationInput, Prisma.NoticiaUncheckedUpdateManyInput>
  /**
   * Filter which Noticias to update
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * Limit how many Noticias to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Noticia upsert
 */
export type NoticiaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * The filter to search for the Noticia to update in case it exists.
   */
  where: Prisma.NoticiaWhereUniqueInput
  /**
   * In case the Noticia found by the `where` argument doesn't exist, create a new Noticia with this data.
   */
  create: Prisma.XOR<Prisma.NoticiaCreateInput, Prisma.NoticiaUncheckedCreateInput>
  /**
   * In case the Noticia was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NoticiaUpdateInput, Prisma.NoticiaUncheckedUpdateInput>
}

/**
 * Noticia delete
 */
export type NoticiaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
  /**
   * Filter which Noticia to delete.
   */
  where: Prisma.NoticiaWhereUniqueInput
}

/**
 * Noticia deleteMany
 */
export type NoticiaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Noticias to delete
   */
  where?: Prisma.NoticiaWhereInput
  /**
   * Limit how many Noticias to delete.
   */
  limit?: number
}

/**
 * Noticia.grupo
 */
export type Noticia$grupoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Grupo
   */
  select?: Prisma.GrupoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Grupo
   */
  omit?: Prisma.GrupoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GrupoInclude<ExtArgs> | null
  where?: Prisma.GrupoWhereInput
}

/**
 * Noticia without action
 */
export type NoticiaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Noticia
   */
  select?: Prisma.NoticiaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Noticia
   */
  omit?: Prisma.NoticiaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NoticiaInclude<ExtArgs> | null
}
