
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Time` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Time
 * 
 */
export type TimeModel = runtime.Types.Result.DefaultSelection<Prisma.$TimePayload>

export type AggregateTime = {
  _count: TimeCountAggregateOutputType | null
  _avg: TimeAvgAggregateOutputType | null
  _sum: TimeSumAggregateOutputType | null
  _min: TimeMinAggregateOutputType | null
  _max: TimeMaxAggregateOutputType | null
}

export type TimeAvgAggregateOutputType = {
  vitorias: number | null
  empates: number | null
  derrotas: number | null
  golsPro: number | null
  golsContra: number | null
  saldoGols: number | null
  pontos: number | null
}

export type TimeSumAggregateOutputType = {
  vitorias: number | null
  empates: number | null
  derrotas: number | null
  golsPro: number | null
  golsContra: number | null
  saldoGols: number | null
  pontos: number | null
}

export type TimeMinAggregateOutputType = {
  id: string | null
  nome: string | null
  sigla: string | null
  bandeira: string | null
  grupoId: string | null
  vitorias: number | null
  empates: number | null
  derrotas: number | null
  golsPro: number | null
  golsContra: number | null
  saldoGols: number | null
  pontos: number | null
  classificado: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TimeMaxAggregateOutputType = {
  id: string | null
  nome: string | null
  sigla: string | null
  bandeira: string | null
  grupoId: string | null
  vitorias: number | null
  empates: number | null
  derrotas: number | null
  golsPro: number | null
  golsContra: number | null
  saldoGols: number | null
  pontos: number | null
  classificado: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TimeCountAggregateOutputType = {
  id: number
  nome: number
  sigla: number
  bandeira: number
  grupoId: number
  vitorias: number
  empates: number
  derrotas: number
  golsPro: number
  golsContra: number
  saldoGols: number
  pontos: number
  classificado: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TimeAvgAggregateInputType = {
  vitorias?: true
  empates?: true
  derrotas?: true
  golsPro?: true
  golsContra?: true
  saldoGols?: true
  pontos?: true
}

export type TimeSumAggregateInputType = {
  vitorias?: true
  empates?: true
  derrotas?: true
  golsPro?: true
  golsContra?: true
  saldoGols?: true
  pontos?: true
}

export type TimeMinAggregateInputType = {
  id?: true
  nome?: true
  sigla?: true
  bandeira?: true
  grupoId?: true
  vitorias?: true
  empates?: true
  derrotas?: true
  golsPro?: true
  golsContra?: true
  saldoGols?: true
  pontos?: true
  classificado?: true
  createdAt?: true
  updatedAt?: true
}

export type TimeMaxAggregateInputType = {
  id?: true
  nome?: true
  sigla?: true
  bandeira?: true
  grupoId?: true
  vitorias?: true
  empates?: true
  derrotas?: true
  golsPro?: true
  golsContra?: true
  saldoGols?: true
  pontos?: true
  classificado?: true
  createdAt?: true
  updatedAt?: true
}

export type TimeCountAggregateInputType = {
  id?: true
  nome?: true
  sigla?: true
  bandeira?: true
  grupoId?: true
  vitorias?: true
  empates?: true
  derrotas?: true
  golsPro?: true
  golsContra?: true
  saldoGols?: true
  pontos?: true
  classificado?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TimeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Time to aggregate.
   */
  where?: Prisma.TimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Times to fetch.
   */
  orderBy?: Prisma.TimeOrderByWithRelationInput | Prisma.TimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Times
  **/
  _count?: true | TimeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TimeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TimeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TimeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TimeMaxAggregateInputType
}

export type GetTimeAggregateType<T extends TimeAggregateArgs> = {
      [P in keyof T & keyof AggregateTime]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTime[P]>
    : Prisma.GetScalarType<T[P], AggregateTime[P]>
}




export type TimeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TimeWhereInput
  orderBy?: Prisma.TimeOrderByWithAggregationInput | Prisma.TimeOrderByWithAggregationInput[]
  by: Prisma.TimeScalarFieldEnum[] | Prisma.TimeScalarFieldEnum
  having?: Prisma.TimeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TimeCountAggregateInputType | true
  _avg?: TimeAvgAggregateInputType
  _sum?: TimeSumAggregateInputType
  _min?: TimeMinAggregateInputType
  _max?: TimeMaxAggregateInputType
}

export type TimeGroupByOutputType = {
  id: string
  nome: string
  sigla: string
  bandeira: string
  grupoId: string
  vitorias: number
  empates: number
  derrotas: number
  golsPro: number
  golsContra: number
  saldoGols: number
  pontos: number
  classificado: boolean
  createdAt: Date
  updatedAt: Date
  _count: TimeCountAggregateOutputType | null
  _avg: TimeAvgAggregateOutputType | null
  _sum: TimeSumAggregateOutputType | null
  _min: TimeMinAggregateOutputType | null
  _max: TimeMaxAggregateOutputType | null
}

export type GetTimeGroupByPayload<T extends TimeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TimeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TimeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TimeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TimeGroupByOutputType[P]>
      }
    >
  >



export type TimeWhereInput = {
  AND?: Prisma.TimeWhereInput | Prisma.TimeWhereInput[]
  OR?: Prisma.TimeWhereInput[]
  NOT?: Prisma.TimeWhereInput | Prisma.TimeWhereInput[]
  id?: Prisma.StringFilter<"Time"> | string
  nome?: Prisma.StringFilter<"Time"> | string
  sigla?: Prisma.StringFilter<"Time"> | string
  bandeira?: Prisma.StringFilter<"Time"> | string
  grupoId?: Prisma.StringFilter<"Time"> | string
  vitorias?: Prisma.IntFilter<"Time"> | number
  empates?: Prisma.IntFilter<"Time"> | number
  derrotas?: Prisma.IntFilter<"Time"> | number
  golsPro?: Prisma.IntFilter<"Time"> | number
  golsContra?: Prisma.IntFilter<"Time"> | number
  saldoGols?: Prisma.IntFilter<"Time"> | number
  pontos?: Prisma.IntFilter<"Time"> | number
  classificado?: Prisma.BoolFilter<"Time"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Time"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Time"> | Date | string
  grupo?: Prisma.XOR<Prisma.GrupoScalarRelationFilter, Prisma.GrupoWhereInput>
  jogosCasa?: Prisma.JogoListRelationFilter
  jogosFora?: Prisma.JogoListRelationFilter
}

export type TimeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sigla?: Prisma.SortOrder
  bandeira?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
  classificado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  grupo?: Prisma.GrupoOrderByWithRelationInput
  jogosCasa?: Prisma.JogoOrderByRelationAggregateInput
  jogosFora?: Prisma.JogoOrderByRelationAggregateInput
}

export type TimeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  nome?: string
  sigla?: string
  nome_grupoId?: Prisma.TimeNomeGrupoIdCompoundUniqueInput
  AND?: Prisma.TimeWhereInput | Prisma.TimeWhereInput[]
  OR?: Prisma.TimeWhereInput[]
  NOT?: Prisma.TimeWhereInput | Prisma.TimeWhereInput[]
  bandeira?: Prisma.StringFilter<"Time"> | string
  grupoId?: Prisma.StringFilter<"Time"> | string
  vitorias?: Prisma.IntFilter<"Time"> | number
  empates?: Prisma.IntFilter<"Time"> | number
  derrotas?: Prisma.IntFilter<"Time"> | number
  golsPro?: Prisma.IntFilter<"Time"> | number
  golsContra?: Prisma.IntFilter<"Time"> | number
  saldoGols?: Prisma.IntFilter<"Time"> | number
  pontos?: Prisma.IntFilter<"Time"> | number
  classificado?: Prisma.BoolFilter<"Time"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Time"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Time"> | Date | string
  grupo?: Prisma.XOR<Prisma.GrupoScalarRelationFilter, Prisma.GrupoWhereInput>
  jogosCasa?: Prisma.JogoListRelationFilter
  jogosFora?: Prisma.JogoListRelationFilter
}, "id" | "nome" | "sigla" | "nome_grupoId">

export type TimeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sigla?: Prisma.SortOrder
  bandeira?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
  classificado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TimeCountOrderByAggregateInput
  _avg?: Prisma.TimeAvgOrderByAggregateInput
  _max?: Prisma.TimeMaxOrderByAggregateInput
  _min?: Prisma.TimeMinOrderByAggregateInput
  _sum?: Prisma.TimeSumOrderByAggregateInput
}

export type TimeScalarWhereWithAggregatesInput = {
  AND?: Prisma.TimeScalarWhereWithAggregatesInput | Prisma.TimeScalarWhereWithAggregatesInput[]
  OR?: Prisma.TimeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TimeScalarWhereWithAggregatesInput | Prisma.TimeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Time"> | string
  nome?: Prisma.StringWithAggregatesFilter<"Time"> | string
  sigla?: Prisma.StringWithAggregatesFilter<"Time"> | string
  bandeira?: Prisma.StringWithAggregatesFilter<"Time"> | string
  grupoId?: Prisma.StringWithAggregatesFilter<"Time"> | string
  vitorias?: Prisma.IntWithAggregatesFilter<"Time"> | number
  empates?: Prisma.IntWithAggregatesFilter<"Time"> | number
  derrotas?: Prisma.IntWithAggregatesFilter<"Time"> | number
  golsPro?: Prisma.IntWithAggregatesFilter<"Time"> | number
  golsContra?: Prisma.IntWithAggregatesFilter<"Time"> | number
  saldoGols?: Prisma.IntWithAggregatesFilter<"Time"> | number
  pontos?: Prisma.IntWithAggregatesFilter<"Time"> | number
  classificado?: Prisma.BoolWithAggregatesFilter<"Time"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Time"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Time"> | Date | string
}

export type TimeCreateInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  grupo: Prisma.GrupoCreateNestedOneWithoutTimesInput
  jogosCasa?: Prisma.JogoCreateNestedManyWithoutTimeCasaInput
  jogosFora?: Prisma.JogoCreateNestedManyWithoutTimeForaInput
}

export type TimeUncheckedCreateInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  grupoId: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  jogosCasa?: Prisma.JogoUncheckedCreateNestedManyWithoutTimeCasaInput
  jogosFora?: Prisma.JogoUncheckedCreateNestedManyWithoutTimeForaInput
}

export type TimeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grupo?: Prisma.GrupoUpdateOneRequiredWithoutTimesNestedInput
  jogosCasa?: Prisma.JogoUpdateManyWithoutTimeCasaNestedInput
  jogosFora?: Prisma.JogoUpdateManyWithoutTimeForaNestedInput
}

export type TimeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  grupoId?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogosCasa?: Prisma.JogoUncheckedUpdateManyWithoutTimeCasaNestedInput
  jogosFora?: Prisma.JogoUncheckedUpdateManyWithoutTimeForaNestedInput
}

export type TimeCreateManyInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  grupoId: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  grupoId?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TimeListRelationFilter = {
  every?: Prisma.TimeWhereInput
  some?: Prisma.TimeWhereInput
  none?: Prisma.TimeWhereInput
}

export type TimeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TimeNomeGrupoIdCompoundUniqueInput = {
  nome: string
  grupoId: string
}

export type TimeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sigla?: Prisma.SortOrder
  bandeira?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
  classificado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeAvgOrderByAggregateInput = {
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
}

export type TimeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sigla?: Prisma.SortOrder
  bandeira?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
  classificado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  nome?: Prisma.SortOrder
  sigla?: Prisma.SortOrder
  bandeira?: Prisma.SortOrder
  grupoId?: Prisma.SortOrder
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
  classificado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TimeSumOrderByAggregateInput = {
  vitorias?: Prisma.SortOrder
  empates?: Prisma.SortOrder
  derrotas?: Prisma.SortOrder
  golsPro?: Prisma.SortOrder
  golsContra?: Prisma.SortOrder
  saldoGols?: Prisma.SortOrder
  pontos?: Prisma.SortOrder
}

export type TimeScalarRelationFilter = {
  is?: Prisma.TimeWhereInput
  isNot?: Prisma.TimeWhereInput
}

export type TimeCreateNestedManyWithoutGrupoInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutGrupoInput, Prisma.TimeUncheckedCreateWithoutGrupoInput> | Prisma.TimeCreateWithoutGrupoInput[] | Prisma.TimeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutGrupoInput | Prisma.TimeCreateOrConnectWithoutGrupoInput[]
  createMany?: Prisma.TimeCreateManyGrupoInputEnvelope
  connect?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
}

export type TimeUncheckedCreateNestedManyWithoutGrupoInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutGrupoInput, Prisma.TimeUncheckedCreateWithoutGrupoInput> | Prisma.TimeCreateWithoutGrupoInput[] | Prisma.TimeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutGrupoInput | Prisma.TimeCreateOrConnectWithoutGrupoInput[]
  createMany?: Prisma.TimeCreateManyGrupoInputEnvelope
  connect?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
}

export type TimeUpdateManyWithoutGrupoNestedInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutGrupoInput, Prisma.TimeUncheckedCreateWithoutGrupoInput> | Prisma.TimeCreateWithoutGrupoInput[] | Prisma.TimeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutGrupoInput | Prisma.TimeCreateOrConnectWithoutGrupoInput[]
  upsert?: Prisma.TimeUpsertWithWhereUniqueWithoutGrupoInput | Prisma.TimeUpsertWithWhereUniqueWithoutGrupoInput[]
  createMany?: Prisma.TimeCreateManyGrupoInputEnvelope
  set?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  disconnect?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  delete?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  connect?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  update?: Prisma.TimeUpdateWithWhereUniqueWithoutGrupoInput | Prisma.TimeUpdateWithWhereUniqueWithoutGrupoInput[]
  updateMany?: Prisma.TimeUpdateManyWithWhereWithoutGrupoInput | Prisma.TimeUpdateManyWithWhereWithoutGrupoInput[]
  deleteMany?: Prisma.TimeScalarWhereInput | Prisma.TimeScalarWhereInput[]
}

export type TimeUncheckedUpdateManyWithoutGrupoNestedInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutGrupoInput, Prisma.TimeUncheckedCreateWithoutGrupoInput> | Prisma.TimeCreateWithoutGrupoInput[] | Prisma.TimeUncheckedCreateWithoutGrupoInput[]
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutGrupoInput | Prisma.TimeCreateOrConnectWithoutGrupoInput[]
  upsert?: Prisma.TimeUpsertWithWhereUniqueWithoutGrupoInput | Prisma.TimeUpsertWithWhereUniqueWithoutGrupoInput[]
  createMany?: Prisma.TimeCreateManyGrupoInputEnvelope
  set?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  disconnect?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  delete?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  connect?: Prisma.TimeWhereUniqueInput | Prisma.TimeWhereUniqueInput[]
  update?: Prisma.TimeUpdateWithWhereUniqueWithoutGrupoInput | Prisma.TimeUpdateWithWhereUniqueWithoutGrupoInput[]
  updateMany?: Prisma.TimeUpdateManyWithWhereWithoutGrupoInput | Prisma.TimeUpdateManyWithWhereWithoutGrupoInput[]
  deleteMany?: Prisma.TimeScalarWhereInput | Prisma.TimeScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type TimeCreateNestedOneWithoutJogosCasaInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutJogosCasaInput, Prisma.TimeUncheckedCreateWithoutJogosCasaInput>
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutJogosCasaInput
  connect?: Prisma.TimeWhereUniqueInput
}

export type TimeCreateNestedOneWithoutJogosForaInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutJogosForaInput, Prisma.TimeUncheckedCreateWithoutJogosForaInput>
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutJogosForaInput
  connect?: Prisma.TimeWhereUniqueInput
}

export type TimeUpdateOneRequiredWithoutJogosCasaNestedInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutJogosCasaInput, Prisma.TimeUncheckedCreateWithoutJogosCasaInput>
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutJogosCasaInput
  upsert?: Prisma.TimeUpsertWithoutJogosCasaInput
  connect?: Prisma.TimeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TimeUpdateToOneWithWhereWithoutJogosCasaInput, Prisma.TimeUpdateWithoutJogosCasaInput>, Prisma.TimeUncheckedUpdateWithoutJogosCasaInput>
}

export type TimeUpdateOneRequiredWithoutJogosForaNestedInput = {
  create?: Prisma.XOR<Prisma.TimeCreateWithoutJogosForaInput, Prisma.TimeUncheckedCreateWithoutJogosForaInput>
  connectOrCreate?: Prisma.TimeCreateOrConnectWithoutJogosForaInput
  upsert?: Prisma.TimeUpsertWithoutJogosForaInput
  connect?: Prisma.TimeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TimeUpdateToOneWithWhereWithoutJogosForaInput, Prisma.TimeUpdateWithoutJogosForaInput>, Prisma.TimeUncheckedUpdateWithoutJogosForaInput>
}

export type TimeCreateWithoutGrupoInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  jogosCasa?: Prisma.JogoCreateNestedManyWithoutTimeCasaInput
  jogosFora?: Prisma.JogoCreateNestedManyWithoutTimeForaInput
}

export type TimeUncheckedCreateWithoutGrupoInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  jogosCasa?: Prisma.JogoUncheckedCreateNestedManyWithoutTimeCasaInput
  jogosFora?: Prisma.JogoUncheckedCreateNestedManyWithoutTimeForaInput
}

export type TimeCreateOrConnectWithoutGrupoInput = {
  where: Prisma.TimeWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeCreateWithoutGrupoInput, Prisma.TimeUncheckedCreateWithoutGrupoInput>
}

export type TimeCreateManyGrupoInputEnvelope = {
  data: Prisma.TimeCreateManyGrupoInput | Prisma.TimeCreateManyGrupoInput[]
  skipDuplicates?: boolean
}

export type TimeUpsertWithWhereUniqueWithoutGrupoInput = {
  where: Prisma.TimeWhereUniqueInput
  update: Prisma.XOR<Prisma.TimeUpdateWithoutGrupoInput, Prisma.TimeUncheckedUpdateWithoutGrupoInput>
  create: Prisma.XOR<Prisma.TimeCreateWithoutGrupoInput, Prisma.TimeUncheckedCreateWithoutGrupoInput>
}

export type TimeUpdateWithWhereUniqueWithoutGrupoInput = {
  where: Prisma.TimeWhereUniqueInput
  data: Prisma.XOR<Prisma.TimeUpdateWithoutGrupoInput, Prisma.TimeUncheckedUpdateWithoutGrupoInput>
}

export type TimeUpdateManyWithWhereWithoutGrupoInput = {
  where: Prisma.TimeScalarWhereInput
  data: Prisma.XOR<Prisma.TimeUpdateManyMutationInput, Prisma.TimeUncheckedUpdateManyWithoutGrupoInput>
}

export type TimeScalarWhereInput = {
  AND?: Prisma.TimeScalarWhereInput | Prisma.TimeScalarWhereInput[]
  OR?: Prisma.TimeScalarWhereInput[]
  NOT?: Prisma.TimeScalarWhereInput | Prisma.TimeScalarWhereInput[]
  id?: Prisma.StringFilter<"Time"> | string
  nome?: Prisma.StringFilter<"Time"> | string
  sigla?: Prisma.StringFilter<"Time"> | string
  bandeira?: Prisma.StringFilter<"Time"> | string
  grupoId?: Prisma.StringFilter<"Time"> | string
  vitorias?: Prisma.IntFilter<"Time"> | number
  empates?: Prisma.IntFilter<"Time"> | number
  derrotas?: Prisma.IntFilter<"Time"> | number
  golsPro?: Prisma.IntFilter<"Time"> | number
  golsContra?: Prisma.IntFilter<"Time"> | number
  saldoGols?: Prisma.IntFilter<"Time"> | number
  pontos?: Prisma.IntFilter<"Time"> | number
  classificado?: Prisma.BoolFilter<"Time"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Time"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Time"> | Date | string
}

export type TimeCreateWithoutJogosCasaInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  grupo: Prisma.GrupoCreateNestedOneWithoutTimesInput
  jogosFora?: Prisma.JogoCreateNestedManyWithoutTimeForaInput
}

export type TimeUncheckedCreateWithoutJogosCasaInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  grupoId: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  jogosFora?: Prisma.JogoUncheckedCreateNestedManyWithoutTimeForaInput
}

export type TimeCreateOrConnectWithoutJogosCasaInput = {
  where: Prisma.TimeWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeCreateWithoutJogosCasaInput, Prisma.TimeUncheckedCreateWithoutJogosCasaInput>
}

export type TimeCreateWithoutJogosForaInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  grupo: Prisma.GrupoCreateNestedOneWithoutTimesInput
  jogosCasa?: Prisma.JogoCreateNestedManyWithoutTimeCasaInput
}

export type TimeUncheckedCreateWithoutJogosForaInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  grupoId: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  jogosCasa?: Prisma.JogoUncheckedCreateNestedManyWithoutTimeCasaInput
}

export type TimeCreateOrConnectWithoutJogosForaInput = {
  where: Prisma.TimeWhereUniqueInput
  create: Prisma.XOR<Prisma.TimeCreateWithoutJogosForaInput, Prisma.TimeUncheckedCreateWithoutJogosForaInput>
}

export type TimeUpsertWithoutJogosCasaInput = {
  update: Prisma.XOR<Prisma.TimeUpdateWithoutJogosCasaInput, Prisma.TimeUncheckedUpdateWithoutJogosCasaInput>
  create: Prisma.XOR<Prisma.TimeCreateWithoutJogosCasaInput, Prisma.TimeUncheckedCreateWithoutJogosCasaInput>
  where?: Prisma.TimeWhereInput
}

export type TimeUpdateToOneWithWhereWithoutJogosCasaInput = {
  where?: Prisma.TimeWhereInput
  data: Prisma.XOR<Prisma.TimeUpdateWithoutJogosCasaInput, Prisma.TimeUncheckedUpdateWithoutJogosCasaInput>
}

export type TimeUpdateWithoutJogosCasaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grupo?: Prisma.GrupoUpdateOneRequiredWithoutTimesNestedInput
  jogosFora?: Prisma.JogoUpdateManyWithoutTimeForaNestedInput
}

export type TimeUncheckedUpdateWithoutJogosCasaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  grupoId?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogosFora?: Prisma.JogoUncheckedUpdateManyWithoutTimeForaNestedInput
}

export type TimeUpsertWithoutJogosForaInput = {
  update: Prisma.XOR<Prisma.TimeUpdateWithoutJogosForaInput, Prisma.TimeUncheckedUpdateWithoutJogosForaInput>
  create: Prisma.XOR<Prisma.TimeCreateWithoutJogosForaInput, Prisma.TimeUncheckedCreateWithoutJogosForaInput>
  where?: Prisma.TimeWhereInput
}

export type TimeUpdateToOneWithWhereWithoutJogosForaInput = {
  where?: Prisma.TimeWhereInput
  data: Prisma.XOR<Prisma.TimeUpdateWithoutJogosForaInput, Prisma.TimeUncheckedUpdateWithoutJogosForaInput>
}

export type TimeUpdateWithoutJogosForaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  grupo?: Prisma.GrupoUpdateOneRequiredWithoutTimesNestedInput
  jogosCasa?: Prisma.JogoUpdateManyWithoutTimeCasaNestedInput
}

export type TimeUncheckedUpdateWithoutJogosForaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  grupoId?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogosCasa?: Prisma.JogoUncheckedUpdateManyWithoutTimeCasaNestedInput
}

export type TimeCreateManyGrupoInput = {
  id?: string
  nome: string
  sigla: string
  bandeira: string
  vitorias?: number
  empates?: number
  derrotas?: number
  golsPro?: number
  golsContra?: number
  saldoGols?: number
  pontos?: number
  classificado?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TimeUpdateWithoutGrupoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogosCasa?: Prisma.JogoUpdateManyWithoutTimeCasaNestedInput
  jogosFora?: Prisma.JogoUpdateManyWithoutTimeForaNestedInput
}

export type TimeUncheckedUpdateWithoutGrupoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jogosCasa?: Prisma.JogoUncheckedUpdateManyWithoutTimeCasaNestedInput
  jogosFora?: Prisma.JogoUncheckedUpdateManyWithoutTimeForaNestedInput
}

export type TimeUncheckedUpdateManyWithoutGrupoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nome?: Prisma.StringFieldUpdateOperationsInput | string
  sigla?: Prisma.StringFieldUpdateOperationsInput | string
  bandeira?: Prisma.StringFieldUpdateOperationsInput | string
  vitorias?: Prisma.IntFieldUpdateOperationsInput | number
  empates?: Prisma.IntFieldUpdateOperationsInput | number
  derrotas?: Prisma.IntFieldUpdateOperationsInput | number
  golsPro?: Prisma.IntFieldUpdateOperationsInput | number
  golsContra?: Prisma.IntFieldUpdateOperationsInput | number
  saldoGols?: Prisma.IntFieldUpdateOperationsInput | number
  pontos?: Prisma.IntFieldUpdateOperationsInput | number
  classificado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type TimeCountOutputType
 */

export type TimeCountOutputType = {
  jogosCasa: number
  jogosFora: number
}

export type TimeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jogosCasa?: boolean | TimeCountOutputTypeCountJogosCasaArgs
  jogosFora?: boolean | TimeCountOutputTypeCountJogosForaArgs
}

/**
 * TimeCountOutputType without action
 */
export type TimeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TimeCountOutputType
   */
  select?: Prisma.TimeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TimeCountOutputType without action
 */
export type TimeCountOutputTypeCountJogosCasaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JogoWhereInput
}

/**
 * TimeCountOutputType without action
 */
export type TimeCountOutputTypeCountJogosForaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JogoWhereInput
}


export type TimeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  sigla?: boolean
  bandeira?: boolean
  grupoId?: boolean
  vitorias?: boolean
  empates?: boolean
  derrotas?: boolean
  golsPro?: boolean
  golsContra?: boolean
  saldoGols?: boolean
  pontos?: boolean
  classificado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  grupo?: boolean | Prisma.GrupoDefaultArgs<ExtArgs>
  jogosCasa?: boolean | Prisma.Time$jogosCasaArgs<ExtArgs>
  jogosFora?: boolean | Prisma.Time$jogosForaArgs<ExtArgs>
  _count?: boolean | Prisma.TimeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["time"]>

export type TimeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  sigla?: boolean
  bandeira?: boolean
  grupoId?: boolean
  vitorias?: boolean
  empates?: boolean
  derrotas?: boolean
  golsPro?: boolean
  golsContra?: boolean
  saldoGols?: boolean
  pontos?: boolean
  classificado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  grupo?: boolean | Prisma.GrupoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["time"]>

export type TimeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  nome?: boolean
  sigla?: boolean
  bandeira?: boolean
  grupoId?: boolean
  vitorias?: boolean
  empates?: boolean
  derrotas?: boolean
  golsPro?: boolean
  golsContra?: boolean
  saldoGols?: boolean
  pontos?: boolean
  classificado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  grupo?: boolean | Prisma.GrupoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["time"]>

export type TimeSelectScalar = {
  id?: boolean
  nome?: boolean
  sigla?: boolean
  bandeira?: boolean
  grupoId?: boolean
  vitorias?: boolean
  empates?: boolean
  derrotas?: boolean
  golsPro?: boolean
  golsContra?: boolean
  saldoGols?: boolean
  pontos?: boolean
  classificado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TimeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "nome" | "sigla" | "bandeira" | "grupoId" | "vitorias" | "empates" | "derrotas" | "golsPro" | "golsContra" | "saldoGols" | "pontos" | "classificado" | "createdAt" | "updatedAt", ExtArgs["result"]["time"]>
export type TimeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.GrupoDefaultArgs<ExtArgs>
  jogosCasa?: boolean | Prisma.Time$jogosCasaArgs<ExtArgs>
  jogosFora?: boolean | Prisma.Time$jogosForaArgs<ExtArgs>
  _count?: boolean | Prisma.TimeCountOutputTypeDefaultArgs<ExtArgs>
}
export type TimeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.GrupoDefaultArgs<ExtArgs>
}
export type TimeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  grupo?: boolean | Prisma.GrupoDefaultArgs<ExtArgs>
}

export type $TimePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Time"
  objects: {
    grupo: Prisma.$GrupoPayload<ExtArgs>
    jogosCasa: Prisma.$JogoPayload<ExtArgs>[]
    jogosFora: Prisma.$JogoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    nome: string
    sigla: string
    bandeira: string
    grupoId: string
    vitorias: number
    empates: number
    derrotas: number
    golsPro: number
    golsContra: number
    saldoGols: number
    pontos: number
    classificado: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["time"]>
  composites: {}
}

export type TimeGetPayload<S extends boolean | null | undefined | TimeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TimePayload, S>

export type TimeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TimeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TimeCountAggregateInputType | true
  }

export interface TimeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Time'], meta: { name: 'Time' } }
  /**
   * Find zero or one Time that matches the filter.
   * @param {TimeFindUniqueArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TimeFindUniqueArgs>(args: Prisma.SelectSubset<T, TimeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Time that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TimeFindUniqueOrThrowArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TimeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TimeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Time that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeFindFirstArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TimeFindFirstArgs>(args?: Prisma.SelectSubset<T, TimeFindFirstArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Time that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeFindFirstOrThrowArgs} args - Arguments to find a Time
   * @example
   * // Get one Time
   * const time = await prisma.time.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TimeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TimeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Times that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Times
   * const times = await prisma.time.findMany()
   * 
   * // Get first 10 Times
   * const times = await prisma.time.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const timeWithIdOnly = await prisma.time.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TimeFindManyArgs>(args?: Prisma.SelectSubset<T, TimeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Time.
   * @param {TimeCreateArgs} args - Arguments to create a Time.
   * @example
   * // Create one Time
   * const Time = await prisma.time.create({
   *   data: {
   *     // ... data to create a Time
   *   }
   * })
   * 
   */
  create<T extends TimeCreateArgs>(args: Prisma.SelectSubset<T, TimeCreateArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Times.
   * @param {TimeCreateManyArgs} args - Arguments to create many Times.
   * @example
   * // Create many Times
   * const time = await prisma.time.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TimeCreateManyArgs>(args?: Prisma.SelectSubset<T, TimeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Times and returns the data saved in the database.
   * @param {TimeCreateManyAndReturnArgs} args - Arguments to create many Times.
   * @example
   * // Create many Times
   * const time = await prisma.time.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Times and only return the `id`
   * const timeWithIdOnly = await prisma.time.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TimeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TimeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Time.
   * @param {TimeDeleteArgs} args - Arguments to delete one Time.
   * @example
   * // Delete one Time
   * const Time = await prisma.time.delete({
   *   where: {
   *     // ... filter to delete one Time
   *   }
   * })
   * 
   */
  delete<T extends TimeDeleteArgs>(args: Prisma.SelectSubset<T, TimeDeleteArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Time.
   * @param {TimeUpdateArgs} args - Arguments to update one Time.
   * @example
   * // Update one Time
   * const time = await prisma.time.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TimeUpdateArgs>(args: Prisma.SelectSubset<T, TimeUpdateArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Times.
   * @param {TimeDeleteManyArgs} args - Arguments to filter Times to delete.
   * @example
   * // Delete a few Times
   * const { count } = await prisma.time.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TimeDeleteManyArgs>(args?: Prisma.SelectSubset<T, TimeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Times.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Times
   * const time = await prisma.time.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TimeUpdateManyArgs>(args: Prisma.SelectSubset<T, TimeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Times and returns the data updated in the database.
   * @param {TimeUpdateManyAndReturnArgs} args - Arguments to update many Times.
   * @example
   * // Update many Times
   * const time = await prisma.time.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Times and only return the `id`
   * const timeWithIdOnly = await prisma.time.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TimeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TimeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Time.
   * @param {TimeUpsertArgs} args - Arguments to update or create a Time.
   * @example
   * // Update or create a Time
   * const time = await prisma.time.upsert({
   *   create: {
   *     // ... data to create a Time
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Time we want to update
   *   }
   * })
   */
  upsert<T extends TimeUpsertArgs>(args: Prisma.SelectSubset<T, TimeUpsertArgs<ExtArgs>>): Prisma.Prisma__TimeClient<runtime.Types.Result.GetResult<Prisma.$TimePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Times.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeCountArgs} args - Arguments to filter Times to count.
   * @example
   * // Count the number of Times
   * const count = await prisma.time.count({
   *   where: {
   *     // ... the filter for the Times we want to count
   *   }
   * })
  **/
  count<T extends TimeCountArgs>(
    args?: Prisma.Subset<T, TimeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TimeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Time.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TimeAggregateArgs>(args: Prisma.Subset<T, TimeAggregateArgs>): Prisma.PrismaPromise<GetTimeAggregateType<T>>

  /**
   * Group by Time.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TimeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TimeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TimeGroupByArgs['orderBy'] }
      : { orderBy?: TimeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TimeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTimeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Time model
 */
readonly fields: TimeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Time.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TimeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  grupo<T extends Prisma.GrupoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GrupoDefaultArgs<ExtArgs>>): Prisma.Prisma__GrupoClient<runtime.Types.Result.GetResult<Prisma.$GrupoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  jogosCasa<T extends Prisma.Time$jogosCasaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Time$jogosCasaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JogoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  jogosFora<T extends Prisma.Time$jogosForaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Time$jogosForaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JogoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Time model
 */
export interface TimeFieldRefs {
  readonly id: Prisma.FieldRef<"Time", 'String'>
  readonly nome: Prisma.FieldRef<"Time", 'String'>
  readonly sigla: Prisma.FieldRef<"Time", 'String'>
  readonly bandeira: Prisma.FieldRef<"Time", 'String'>
  readonly grupoId: Prisma.FieldRef<"Time", 'String'>
  readonly vitorias: Prisma.FieldRef<"Time", 'Int'>
  readonly empates: Prisma.FieldRef<"Time", 'Int'>
  readonly derrotas: Prisma.FieldRef<"Time", 'Int'>
  readonly golsPro: Prisma.FieldRef<"Time", 'Int'>
  readonly golsContra: Prisma.FieldRef<"Time", 'Int'>
  readonly saldoGols: Prisma.FieldRef<"Time", 'Int'>
  readonly pontos: Prisma.FieldRef<"Time", 'Int'>
  readonly classificado: Prisma.FieldRef<"Time", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Time", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Time", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Time findUnique
 */
export type TimeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * Filter, which Time to fetch.
   */
  where: Prisma.TimeWhereUniqueInput
}

/**
 * Time findUniqueOrThrow
 */
export type TimeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * Filter, which Time to fetch.
   */
  where: Prisma.TimeWhereUniqueInput
}

/**
 * Time findFirst
 */
export type TimeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * Filter, which Time to fetch.
   */
  where?: Prisma.TimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Times to fetch.
   */
  orderBy?: Prisma.TimeOrderByWithRelationInput | Prisma.TimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Times.
   */
  cursor?: Prisma.TimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Times.
   */
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * Time findFirstOrThrow
 */
export type TimeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * Filter, which Time to fetch.
   */
  where?: Prisma.TimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Times to fetch.
   */
  orderBy?: Prisma.TimeOrderByWithRelationInput | Prisma.TimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Times.
   */
  cursor?: Prisma.TimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Times.
   */
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * Time findMany
 */
export type TimeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * Filter, which Times to fetch.
   */
  where?: Prisma.TimeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Times to fetch.
   */
  orderBy?: Prisma.TimeOrderByWithRelationInput | Prisma.TimeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Times.
   */
  cursor?: Prisma.TimeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Times from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Times.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Times.
   */
  distinct?: Prisma.TimeScalarFieldEnum | Prisma.TimeScalarFieldEnum[]
}

/**
 * Time create
 */
export type TimeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * The data needed to create a Time.
   */
  data: Prisma.XOR<Prisma.TimeCreateInput, Prisma.TimeUncheckedCreateInput>
}

/**
 * Time createMany
 */
export type TimeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Times.
   */
  data: Prisma.TimeCreateManyInput | Prisma.TimeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Time createManyAndReturn
 */
export type TimeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * The data used to create many Times.
   */
  data: Prisma.TimeCreateManyInput | Prisma.TimeCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Time update
 */
export type TimeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * The data needed to update a Time.
   */
  data: Prisma.XOR<Prisma.TimeUpdateInput, Prisma.TimeUncheckedUpdateInput>
  /**
   * Choose, which Time to update.
   */
  where: Prisma.TimeWhereUniqueInput
}

/**
 * Time updateMany
 */
export type TimeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Times.
   */
  data: Prisma.XOR<Prisma.TimeUpdateManyMutationInput, Prisma.TimeUncheckedUpdateManyInput>
  /**
   * Filter which Times to update
   */
  where?: Prisma.TimeWhereInput
  /**
   * Limit how many Times to update.
   */
  limit?: number
}

/**
 * Time updateManyAndReturn
 */
export type TimeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * The data used to update Times.
   */
  data: Prisma.XOR<Prisma.TimeUpdateManyMutationInput, Prisma.TimeUncheckedUpdateManyInput>
  /**
   * Filter which Times to update
   */
  where?: Prisma.TimeWhereInput
  /**
   * Limit how many Times to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Time upsert
 */
export type TimeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * The filter to search for the Time to update in case it exists.
   */
  where: Prisma.TimeWhereUniqueInput
  /**
   * In case the Time found by the `where` argument doesn't exist, create a new Time with this data.
   */
  create: Prisma.XOR<Prisma.TimeCreateInput, Prisma.TimeUncheckedCreateInput>
  /**
   * In case the Time was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TimeUpdateInput, Prisma.TimeUncheckedUpdateInput>
}

/**
 * Time delete
 */
export type TimeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
  /**
   * Filter which Time to delete.
   */
  where: Prisma.TimeWhereUniqueInput
}

/**
 * Time deleteMany
 */
export type TimeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Times to delete
   */
  where?: Prisma.TimeWhereInput
  /**
   * Limit how many Times to delete.
   */
  limit?: number
}

/**
 * Time.jogosCasa
 */
export type Time$jogosCasaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jogo
   */
  select?: Prisma.JogoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jogo
   */
  omit?: Prisma.JogoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JogoInclude<ExtArgs> | null
  where?: Prisma.JogoWhereInput
  orderBy?: Prisma.JogoOrderByWithRelationInput | Prisma.JogoOrderByWithRelationInput[]
  cursor?: Prisma.JogoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JogoScalarFieldEnum | Prisma.JogoScalarFieldEnum[]
}

/**
 * Time.jogosFora
 */
export type Time$jogosForaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Jogo
   */
  select?: Prisma.JogoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Jogo
   */
  omit?: Prisma.JogoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JogoInclude<ExtArgs> | null
  where?: Prisma.JogoWhereInput
  orderBy?: Prisma.JogoOrderByWithRelationInput | Prisma.JogoOrderByWithRelationInput[]
  cursor?: Prisma.JogoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JogoScalarFieldEnum | Prisma.JogoScalarFieldEnum[]
}

/**
 * Time without action
 */
export type TimeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Time
   */
  select?: Prisma.TimeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Time
   */
  omit?: Prisma.TimeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TimeInclude<ExtArgs> | null
}
