
import UltimoResultado from "../../components/UltimoResultado";
import GroupClassificationHeader from "../../components/Groups/GroupClassificationHeader";
import GroupClassificationCard from "../../components/Groups/GroupClassificationCard";

import brasil from "../../assets/TEST/BR.png";
import croacia from "../../assets/TEST/BR.png";
import marrocos from "../../assets/TEST/BR.png";
import camaroes from "../../assets/TEST/BR.png";

const groupA = [
  {
    id: 1,
    position: 1,
    name: "Brasil",
    abbreviation: "BRA",
    flag: brasil,
    matches: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 7,
    goalsAgainst: 2,
    goalDifference: 5,
    points: 7,
    qualified: true,
  },
  {
    id: 2,
    position: 2,
    name: "Croácia",
    abbreviation: "CRO",
    flag: croacia,
    matches: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    points: 4,
    qualified: true,
  },
  {
    id: 3,
    position: 3,
    name: "Marrocos",
    abbreviation: "MAR",
    flag: marrocos,
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
    points: 3,
  },
  {
    id: 4,
    position: 4,
    name: "Camarões",
    abbreviation: "CMR",
    flag: camaroes,
    matches: 3,
    wins: 0,
    draws: 2,
    losses: 1,
    goalsFor: 2,
    goalsAgainst: 4,
    goalDifference: -2,
    points: 2,
  },
];

const groupB = [
  {
    id: 1,
    position: 5,
    name: "Brasil",
    abbreviation: "BRA",
    flag: brasil,
    matches: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 7,
    goalsAgainst: 2,
    goalDifference: 5,
    points: 7,
    qualified: true,
  },
  {
    id: 2,
    position: 6,
    name: "Croácia",
    abbreviation: "CRO",
    flag: croacia,
    matches: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    points: 4,
    qualified: true,
  },
  {
    id: 3,
    position: 7,
    name: "Marrocos",
    abbreviation: "MAR",
    flag: marrocos,
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
    points: 3,
  },
  {
    id: 4,
    position: 8,
    name: "Camarões",
    abbreviation: "CMR",
    flag: camaroes,
    matches: 3,
    wins: 0,
    draws: 2,
    losses: 1,
    goalsFor: 2,
    goalsAgainst: 4,
    goalDifference: -2,
    points: 2,
  },
];

const groupC = [
  {
    id: 1,
    position: 9,
    name: "Brasil",
    abbreviation: "BRA",
    flag: brasil,
    matches: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 7,
    goalsAgainst: 2,
    goalDifference: 5,
    points: 7,
    qualified: true,
  },
  {
    id: 2,
    position: 10,
    name: "Croácia",
    abbreviation: "CRO",
    flag: croacia,
    matches: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    points: 4,
    qualified: true,
  },
  {
    id: 3,
    position: 11,
    name: "Marrocos",
    abbreviation: "MAR",
    flag: marrocos,
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
    points: 3,
  },
  {
    id: 4,
    position: 12,
    name: "Camarões",
    abbreviation: "CMR",
    flag: camaroes,
    matches: 3,
    wins: 0,
    draws: 2,
    losses: 1,
    goalsFor: 2,
    goalsAgainst: 4,
    goalDifference: -2,
    points: 2,
  },
];

const groupD = [
  {
    id: 1,
    position: 13,
    name: "Brasil",
    abbreviation: "BRA",
    flag: brasil,
    matches: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 7,
    goalsAgainst: 2,
    goalDifference: 5,
    points: 7,
    qualified: true,
  },
  {
    id: 2,
    position: 14,
    name: "Croácia",
    abbreviation: "CRO",
    flag: croacia,
    matches: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    points: 4,
    qualified: true,
  },
  {
    id: 3,
    position: 15,
    name: "Marrocos",
    abbreviation: "MAR",
    flag: marrocos,
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
    points: 3,
  },
  {
    id: 4,
    position: 16,
    name: "Camarões",
    abbreviation: "CMR",
    flag: camaroes,
    matches: 3,
    wins: 0,
    draws: 2,
    losses: 1,
    goalsFor: 2,
    goalsAgainst: 4,
    goalDifference: -2,
    points: 2,
  },
];

const groupE = [
  {
    id: 1,
    position: 17,
    name: "Brasil",
    abbreviation: "BRA",
    flag: brasil,
    matches: 3,
    wins: 2,
    draws: 1,
    losses: 0,
    goalsFor: 7,
    goalsAgainst: 2,
    goalDifference: 5,
    points: 7,
    qualified: true,
  },
  {
    id: 2,
    position: 18,
    name: "Croácia",
    abbreviation: "CRO",
    flag: croacia,
    matches: 3,
    wins: 1,
    draws: 1,
    losses: 1,
    goalsFor: 4,
    goalsAgainst: 5,
    goalDifference: -1,
    points: 4,
    qualified: true,
  },
  {
    id: 3,
    position: 19,
    name: "Marrocos",
    abbreviation: "MAR",
    flag: marrocos,
    matches: 3,
    wins: 1,
    draws: 0,
    losses: 2,
    goalsFor: 3,
    goalsAgainst: 5,
    goalDifference: -2,
    points: 3,
  },
  {
    id: 4,
    position: 20,
    name: "Camarões",
    abbreviation: "CMR",
    flag: camaroes,
    matches: 3,
    wins: 0,
    draws: 2,
    losses: 1,
    goalsFor: 2,
    goalsAgainst: 4,
    goalDifference: -2,
    points: 2,
  },
];

export default function Home() {
  return (
    <>
        <UltimoResultado/>
        <GroupClassificationHeader/>
        <GroupClassificationCard groupName="Grupo A" teams={groupA}/>
        <GroupClassificationCard groupName="Grupo B" teams={groupB}/>
        <GroupClassificationCard groupName="Grupo C" teams={groupC}/>
        <GroupClassificationCard groupName="Grupo D" teams={groupD}/>
        <GroupClassificationCard groupName="Grupo E" teams={groupE}/>
    </>
    
  );
}
