
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AcaoLog = {
  CRIACAO: 'CRIACAO',
  EDICAO: 'EDICAO',
  EXCLUSAO: 'EXCLUSAO'
} as const

export type AcaoLog = (typeof AcaoLog)[keyof typeof AcaoLog]


export const EntidadeLog = {
  TIME: 'TIME',
  JOGO: 'JOGO',
  NOTICIA: 'NOTICIA',
  GRUPO: 'GRUPO'
} as const

export type EntidadeLog = (typeof EntidadeLog)[keyof typeof EntidadeLog]


export const StatusJogo = {
  PROXIMO: 'PROXIMO',
  CONCLUIDO: 'CONCLUIDO'
} as const

export type StatusJogo = (typeof StatusJogo)[keyof typeof StatusJogo]


export const Roles = {
  admin: 'admin',
  user: 'user'
} as const

export type Roles = (typeof Roles)[keyof typeof Roles]
