
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.js'
export type * from './models/Grupo.js'
export type * from './models/Time.js'
export type * from './models/Jogo.js'
export type * from './models/Noticia.js'
export type * from './models/LogAdmin.js'
export type * from './commonInputTypes.js'